
	.align	16
__MAIN
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,4
	mov	eax,__DATA
	mov	[esp],eax
	call	__bbRestore
	sub	esp,4
	mov	eax,__LIBS
	mov	[esp],eax
	call	__bbLoadLibs
	call	_2_begin
	jmp	_2_leave
_2_begin
	ret
_2_leave
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 0
	.align	16
_fchunkterrain
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,272
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	mov	[ebp-20],ebx
	mov	[ebp-24],ebx
	mov	[ebp-28],ebx
	mov	[ebp-32],ebx
	mov	[ebp-36],ebx
	mov	[ebp-40],ebx
	mov	[ebp-44],ebx
	mov	[ebp-48],ebx
	mov	[ebp-52],ebx
	mov	[ebp-56],ebx
	mov	[ebp-60],ebx
	mov	[ebp-64],ebx
	mov	[ebp-68],ebx
	mov	[ebp-72],ebx
	mov	[ebp-76],ebx
	mov	[ebp-80],ebx
	mov	[ebp-84],ebx
	mov	[ebp-88],ebx
	mov	[ebp-92],ebx
	mov	[ebp-96],ebx
	mov	[ebp-100],ebx
	mov	[ebp-104],ebx
	mov	[ebp-108],ebx
	mov	[ebp-112],ebx
	mov	[ebp-116],ebx
	mov	[ebp-120],ebx
	mov	[ebp-124],ebx
	mov	[ebp-128],ebx
	mov	[ebp-132],ebx
	mov	[ebp-136],ebx
	mov	[ebp-140],ebx
	mov	[ebp-144],ebx
	mov	[ebp-148],ebx
	mov	[ebp-152],ebx
	mov	[ebp-156],ebx
	mov	[ebp-160],ebx
	mov	[ebp-164],ebx
	mov	[ebp-168],ebx
	mov	[ebp-172],ebx
	mov	[ebp-176],ebx
	mov	[ebp-180],ebx
	mov	[ebp-184],ebx
	mov	[ebp-188],ebx
	mov	[ebp-192],ebx
	mov	[ebp-196],ebx
	mov	[ebp-200],ebx
	mov	[ebp-204],ebx
	mov	[ebp-208],ebx
	mov	[ebp-212],ebx
	mov	[ebp-216],ebx
	mov	[ebp-220],ebx
	mov	[ebp-224],ebx
	mov	[ebp-228],ebx
	mov	[ebp-232],ebx
	mov	[ebp-236],ebx
	mov	[ebp-240],ebx
	mov	[ebp-244],ebx
	mov	[ebp-248],ebx
	mov	[ebp-252],ebx
	mov	[ebp-256],ebx
	mov	[ebp-260],ebx
	mov	[ebp-264],ebx
	mov	[ebp-268],ebx
	sub	esp,4
	mov	eax,_tcluster
	mov	[esp],eax
	call	__bbObjDeleteEach
	sub	esp,4
	mov	eax,_tremove_surf
	mov	[esp],eax
	call	__bbObjDeleteEach
	sub	esp,12
	mov	[esp+4],0
	mov	[esp+8],0
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fgetmatelement
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-4],eax
	sub	esp,12
	mov	[esp+4],0
	mov	[esp+8],1
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fgetmatelement
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-8],eax
	sub	esp,12
	mov	[esp+4],0
	mov	[esp+8],2
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fgetmatelement
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-12],eax
	sub	esp,4
	mov	eax,[ebp-4]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,[ebp-4]
	push	ebx
	fld	[esp]
	pop	ebx
	fmulp	st(1)
	mov	ebx,[ebp-8]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-8]
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	faddp	st(1)
	mov	ebx,[ebp-12]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-12]
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	faddp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp],eax
	call	_fsqr
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-16],eax
	sub	esp,12
	mov	[esp+4],1
	mov	[esp+8],0
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fgetmatelement
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-4],eax
	sub	esp,12
	mov	[esp+4],1
	mov	[esp+8],1
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fgetmatelement
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-8],eax
	sub	esp,12
	mov	[esp+4],1
	mov	[esp+8],2
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fgetmatelement
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-12],eax
	sub	esp,4
	mov	eax,[ebp-4]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,[ebp-4]
	push	ebx
	fld	[esp]
	pop	ebx
	fmulp	st(1)
	mov	ebx,[ebp-8]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-8]
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	faddp	st(1)
	mov	ebx,[ebp-12]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-12]
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	faddp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp],eax
	call	_fsqr
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-20],eax
	sub	esp,12
	mov	[esp+4],2
	mov	[esp+8],0
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fgetmatelement
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-4],eax
	sub	esp,12
	mov	[esp+4],2
	mov	[esp+8],1
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fgetmatelement
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-8],eax
	sub	esp,12
	mov	[esp+4],2
	mov	[esp+8],2
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fgetmatelement
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-12],eax
	sub	esp,4
	mov	eax,[ebp-4]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,[ebp-4]
	push	ebx
	fld	[esp]
	pop	ebx
	fmulp	st(1)
	mov	ebx,[ebp-8]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-8]
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	faddp	st(1)
	mov	ebx,[ebp-12]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-12]
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	faddp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp],eax
	call	_fsqr
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-24],eax
	sub	esp,4
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fmeshwidth
	mov	ebx,[ebp+24]
	push	ebx
	fild	[esp]
	pop	ebx
	fdivp	st(1)
	push	eax
	fistp	[esp]
	pop	eax
	push	eax
	fild	[esp]
	pop	eax
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-28],eax
	sub	esp,4
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fmeshheight
	mov	ebx,[ebp+28]
	push	ebx
	fild	[esp]
	pop	ebx
	fdivp	st(1)
	push	eax
	fistp	[esp]
	pop	eax
	push	eax
	fild	[esp]
	pop	eax
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-32],eax
	sub	esp,4
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fmeshdepth
	mov	ebx,[ebp+32]
	push	ebx
	fild	[esp]
	pop	ebx
	fdivp	st(1)
	push	eax
	fistp	[esp]
	pop	eax
	push	eax
	fild	[esp]
	pop	eax
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-36],eax
	sub	esp,4
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fcountsurfaces
	mov	[ebp-40],eax
	mov	[ebp-44],1
	jmp	_24
_25
	sub	esp,8
	mov	eax,[ebp+20]
	mov	[esp],eax
	mov	ebx,[ebp-44]
	mov	[esp+4],ebx
	call	_fgetsurface
	mov	[ebp-48],eax
	sub	esp,4
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_fgetsurfacebrush
	mov	[ebp-52],eax
	mov	[ebp-56],0
	jmp	_26
_27
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexx
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-60],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexy
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-64],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexz
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-68],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexnx
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-72],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexny
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-76],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexnz
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-80],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexalpha
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-84],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexred
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-88],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexgreen
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-92],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexblue
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-96],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexx
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-100],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexy
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-104],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexz
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-108],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexnx
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-112],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexny
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-116],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexnz
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-120],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexalpha
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-124],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexred
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-128],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexgreen
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-132],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexblue
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-136],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexx
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-140],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexy
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-144],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexz
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-148],ebx
	sub	esp,24
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexu
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-152],ebx
	sub	esp,24
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexv
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-156],ebx
	sub	esp,24
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexu
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-160],ebx
	sub	esp,24
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexv
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-164],ebx
	sub	esp,24
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexu
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-168],ebx
	sub	esp,24
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexv
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-172],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexnx
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-176],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexny
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-180],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexnz
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-184],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexalpha
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-188],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexred
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-192],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexgreen
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-196],ebx
	sub	esp,20
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexblue
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-200],ebx
	sub	esp,28
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexx
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp],ebx
	mov	esi,[ebp-28]
	mov	[esp+4],esi
	mov	eax,ebx
	call	_fnearestpower
	mov	ebx,eax
	push	ebx
	fild	[esp]
	pop	ebx
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-204],ebx
	sub	esp,28
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexy
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp],ebx
	mov	esi,[ebp-32]
	mov	[esp+4],esi
	mov	eax,ebx
	call	_fnearestpower
	mov	ebx,eax
	push	ebx
	fild	[esp]
	pop	ebx
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-208],ebx
	sub	esp,28
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexz
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp],ebx
	mov	esi,[ebp-36]
	mov	[esp+4],esi
	mov	eax,ebx
	call	_fnearestpower
	mov	ebx,eax
	push	ebx
	fild	[esp]
	pop	ebx
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-212],ebx
	mov	[ebp-216],0
	sub	esp,8
	lea	eax,[ebp-220]
	mov	[esp],eax
	mov	[esp+4],_tcluster
	call	__bbObjEachFirst
	and	eax,eax
	jz	_7
_28
	mov	eax,[ebp-204]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,0
	mov	ebx,[ebx]
	push	ebx
	fld	[esp]
	pop	ebx
	fucompp
	fnstsw	ax
	sahf
	setz	al
	movzx	eax,al
	mov	[ebp-272],eax
	mov	ebx,[ebp-208]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-220]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	push	esi
	fld	[esp]
	pop	esi
	mov	eax,ebx
	fucompp
	fnstsw	ax
	sahf
	setz	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-272]
	and	eax,ebx
	mov	[ebp-272],eax
	mov	ebx,[ebp-212]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-220]
	mov	esi,[esi]
	add	esi,8
	mov	esi,[esi]
	push	esi
	fld	[esp]
	pop	esi
	mov	eax,ebx
	fucompp
	fnstsw	ax
	sahf
	setz	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-272]
	and	eax,ebx
	and	eax,eax
	jz	_29
	mov	ebx,[ebp-44]
	shl	ebx,byte 2
	mov	esi,[ebp-220]
	mov	esi,[esi]
	add	esi,16
	mov	esi,[esi]
	add	ebx,esi
	mov	ebx,[ebx]
	cmp	ebx,0
	jz	_30
	mov	[ebp-216],1
	sub	esp,28
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+20],0
	mov	[esp+24],1065353216
	mov	[esp+16],0
	mov	ebx,[ebp-68]
	mov	[esp+12],ebx
	mov	esi,[ebp-64]
	mov	[esp+8],esi
	mov	ebx,[ebp-60]
	mov	[esp+4],ebx
	call	_faddvertex
	mov	[ebp-224],eax
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+16],0
	mov	[esp+20],0
	mov	esi,[ebp-156]
	mov	[esp+12],esi
	mov	ebx,[ebp-152]
	mov	[esp+8],ebx
	mov	esi,[ebp-224]
	mov	[esp+4],esi
	call	_fvertextexcoords
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-96]
	mov	[esp+16],ebx
	mov	esi,[ebp-84]
	mov	[esp+20],esi
	mov	esi,[ebp-92]
	mov	[esp+12],esi
	mov	ebx,[ebp-88]
	mov	[esp+8],ebx
	mov	esi,[ebp-224]
	mov	[esp+4],esi
	call	_fvertexcolor
	sub	esp,20
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-76]
	mov	[esp+12],ebx
	mov	esi,[ebp-80]
	mov	[esp+16],esi
	mov	esi,[ebp-72]
	mov	[esp+8],esi
	mov	ebx,[ebp-224]
	mov	[esp+4],ebx
	call	_fvertexnormal
	sub	esp,28
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+20],0
	mov	[esp+24],1065353216
	mov	[esp+16],0
	mov	ebx,[ebp-108]
	mov	[esp+12],ebx
	mov	esi,[ebp-104]
	mov	[esp+8],esi
	mov	ebx,[ebp-100]
	mov	[esp+4],ebx
	call	_faddvertex
	mov	[ebp-228],eax
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+16],0
	mov	[esp+20],0
	mov	esi,[ebp-164]
	mov	[esp+12],esi
	mov	ebx,[ebp-160]
	mov	[esp+8],ebx
	mov	esi,[ebp-228]
	mov	[esp+4],esi
	call	_fvertextexcoords
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-136]
	mov	[esp+16],ebx
	mov	esi,[ebp-124]
	mov	[esp+20],esi
	mov	esi,[ebp-132]
	mov	[esp+12],esi
	mov	ebx,[ebp-128]
	mov	[esp+8],ebx
	mov	esi,[ebp-228]
	mov	[esp+4],esi
	call	_fvertexcolor
	sub	esp,20
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-116]
	mov	[esp+12],ebx
	mov	esi,[ebp-120]
	mov	[esp+16],esi
	mov	esi,[ebp-112]
	mov	[esp+8],esi
	mov	ebx,[ebp-228]
	mov	[esp+4],ebx
	call	_fvertexnormal
	sub	esp,28
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+20],0
	mov	[esp+24],1065353216
	mov	[esp+16],0
	mov	ebx,[ebp-148]
	mov	[esp+12],ebx
	mov	esi,[ebp-144]
	mov	[esp+8],esi
	mov	ebx,[ebp-140]
	mov	[esp+4],ebx
	call	_faddvertex
	mov	[ebp-232],eax
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+16],0
	mov	[esp+20],0
	mov	esi,[ebp-172]
	mov	[esp+12],esi
	mov	ebx,[ebp-168]
	mov	[esp+8],ebx
	mov	esi,[ebp-232]
	mov	[esp+4],esi
	call	_fvertextexcoords
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-200]
	mov	[esp+16],ebx
	mov	esi,[ebp-188]
	mov	[esp+20],esi
	mov	esi,[ebp-196]
	mov	[esp+12],esi
	mov	ebx,[ebp-192]
	mov	[esp+8],ebx
	mov	esi,[ebp-232]
	mov	[esp+4],esi
	call	_fvertexcolor
	sub	esp,20
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-180]
	mov	[esp+12],ebx
	mov	esi,[ebp-184]
	mov	[esp+16],esi
	mov	esi,[ebp-176]
	mov	[esp+8],esi
	mov	ebx,[ebp-232]
	mov	[esp+4],ebx
	call	_fvertexnormal
	sub	esp,16
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-228]
	mov	[esp+8],ebx
	mov	esi,[ebp-232]
	mov	[esp+12],esi
	mov	esi,[ebp-224]
	mov	[esp+4],esi
	call	_faddtriangle
	mov	[ebp-236],eax
	jmp	_7
_30
_29
	sub	esp,4
	lea	eax,[ebp-220]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_28
_7
	cmp	[ebp-216],0
	jnz	_31
	sub	esp,8
	lea	eax,[ebp-220]
	mov	[esp],eax
	mov	[ebp-272],eax
	sub	esp,4
	mov	ebx,_tcluster
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-272]
	mov	[esp+4],ebx
	call	__bbObjStore
	add	[ebp-240],1
	mov	ebx,[ebp-204]
	mov	esi,[ebp-220]
	mov	esi,[esi]
	add	esi,0
	mov	[esi],ebx
	mov	ebx,[ebp-208]
	mov	esi,[ebp-220]
	mov	esi,[esi]
	add	esi,4
	mov	[esi],ebx
	mov	ebx,[ebp-212]
	mov	esi,[ebp-220]
	mov	esi,[esi]
	add	esi,8
	mov	[esi],ebx
	sub	esp,4
	mov	[esp],0
	call	_fcreatemesh
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,12
	mov	[ebx],eax
	mov	[ebp-244],1
	jmp	_32
_33
	sub	esp,8
	mov	eax,[ebp-220]
	mov	eax,[eax]
	add	eax,12
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+4],0
	call	_fcreatesurface
	mov	ebx,[ebp-244]
	shl	ebx,byte 2
	mov	esi,[ebp-220]
	mov	esi,[esi]
	add	esi,16
	mov	esi,[esi]
	add	ebx,esi
	mov	[ebx],eax
	sub	esp,8
	mov	eax,[ebp+20]
	mov	[esp],eax
	mov	ebx,[ebp-244]
	mov	[esp+4],ebx
	call	_fgetsurface
	mov	[ebp-248],eax
	sub	esp,4
	mov	eax,[ebp-248]
	mov	[esp],eax
	call	_fgetsurfacebrush
	mov	[ebp-52],eax
	sub	esp,8
	mov	eax,[ebp-244]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-52]
	mov	[esp+4],ebx
	call	_fpaintsurface
	add	[ebp-244],1
_32
	mov	ebx,[ebp-40]
	cmp	[ebp-244],ebx
	jle	_33
_8
	sub	esp,28
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+20],0
	mov	[esp+24],1065353216
	mov	[esp+16],0
	mov	ebx,[ebp-68]
	mov	[esp+12],ebx
	mov	esi,[ebp-64]
	mov	[esp+8],esi
	mov	ebx,[ebp-60]
	mov	[esp+4],ebx
	call	_faddvertex
	mov	[ebp-224],eax
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+16],0
	mov	[esp+20],0
	mov	esi,[ebp-156]
	mov	[esp+12],esi
	mov	ebx,[ebp-152]
	mov	[esp+8],ebx
	mov	esi,[ebp-224]
	mov	[esp+4],esi
	call	_fvertextexcoords
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-96]
	mov	[esp+16],ebx
	mov	esi,[ebp-84]
	mov	[esp+20],esi
	mov	esi,[ebp-92]
	mov	[esp+12],esi
	mov	ebx,[ebp-88]
	mov	[esp+8],ebx
	mov	esi,[ebp-224]
	mov	[esp+4],esi
	call	_fvertexcolor
	sub	esp,20
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-76]
	mov	[esp+12],ebx
	mov	esi,[ebp-80]
	mov	[esp+16],esi
	mov	esi,[ebp-72]
	mov	[esp+8],esi
	mov	ebx,[ebp-224]
	mov	[esp+4],ebx
	call	_fvertexnormal
	sub	esp,28
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+20],0
	mov	[esp+24],1065353216
	mov	[esp+16],0
	mov	ebx,[ebp-108]
	mov	[esp+12],ebx
	mov	esi,[ebp-104]
	mov	[esp+8],esi
	mov	ebx,[ebp-100]
	mov	[esp+4],ebx
	call	_faddvertex
	mov	[ebp-228],eax
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+16],0
	mov	[esp+20],0
	mov	esi,[ebp-164]
	mov	[esp+12],esi
	mov	ebx,[ebp-160]
	mov	[esp+8],ebx
	mov	esi,[ebp-228]
	mov	[esp+4],esi
	call	_fvertextexcoords
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-136]
	mov	[esp+16],ebx
	mov	esi,[ebp-124]
	mov	[esp+20],esi
	mov	esi,[ebp-132]
	mov	[esp+12],esi
	mov	ebx,[ebp-128]
	mov	[esp+8],ebx
	mov	esi,[ebp-228]
	mov	[esp+4],esi
	call	_fvertexcolor
	sub	esp,20
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-116]
	mov	[esp+12],ebx
	mov	esi,[ebp-120]
	mov	[esp+16],esi
	mov	esi,[ebp-112]
	mov	[esp+8],esi
	mov	ebx,[ebp-228]
	mov	[esp+4],ebx
	call	_fvertexnormal
	sub	esp,28
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+20],0
	mov	[esp+24],1065353216
	mov	[esp+16],0
	mov	ebx,[ebp-148]
	mov	[esp+12],ebx
	mov	esi,[ebp-144]
	mov	[esp+8],esi
	mov	ebx,[ebp-140]
	mov	[esp+4],ebx
	call	_faddvertex
	mov	[ebp-232],eax
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	[esp+16],0
	mov	[esp+20],0
	mov	esi,[ebp-172]
	mov	[esp+12],esi
	mov	ebx,[ebp-168]
	mov	[esp+8],ebx
	mov	esi,[ebp-232]
	mov	[esp+4],esi
	call	_fvertextexcoords
	sub	esp,24
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-200]
	mov	[esp+16],ebx
	mov	esi,[ebp-188]
	mov	[esp+20],esi
	mov	esi,[ebp-196]
	mov	[esp+12],esi
	mov	ebx,[ebp-192]
	mov	[esp+8],ebx
	mov	esi,[ebp-232]
	mov	[esp+4],esi
	call	_fvertexcolor
	sub	esp,20
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-180]
	mov	[esp+12],ebx
	mov	esi,[ebp-184]
	mov	[esp+16],esi
	mov	esi,[ebp-176]
	mov	[esp+8],esi
	mov	ebx,[ebp-232]
	mov	[esp+4],ebx
	call	_fvertexnormal
	sub	esp,16
	mov	eax,[ebp-44]
	shl	eax,byte 2
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	eax,ebx
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-228]
	mov	[esp+8],ebx
	mov	esi,[ebp-232]
	mov	[esp+12],esi
	mov	esi,[ebp-224]
	mov	[esp+4],esi
	call	_faddtriangle
	mov	[ebp-236],eax
_31
	add	[ebp-56],1
_26
	sub	esp,4
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_fcounttriangles
	sub	eax,1
	cmp	[ebp-56],eax
	jle	_27
_6
	add	[ebp-44],1
_24
	mov	ebx,[ebp-40]
	cmp	[ebp-44],ebx
	jle	_25
_5
	sub	esp,8
	lea	eax,[ebp-220]
	mov	[esp],eax
	mov	[esp+4],_tcluster
	call	__bbObjEachFirst
	and	eax,eax
	jz	_9
_34
	sub	esp,8
	lea	eax,[ebp-252]
	mov	[esp],eax
	mov	[esp+4],_tremove_surf
	call	__bbObjEachFirst
	and	eax,eax
	jz	_10
_35
	sub	esp,4
	mov	eax,[ebp-252]
	mov	[esp],eax
	call	__bbObjDelete
	sub	esp,4
	lea	eax,[ebp-252]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_35
_10
	mov	[ebp-256],1
	jmp	_36
_37
	sub	esp,8
	mov	eax,[ebp-220]
	mov	eax,[eax]
	add	eax,12
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-256]
	mov	[esp+4],ebx
	call	_fgetsurface
	mov	[ebp-260],eax
	sub	esp,4
	mov	eax,[ebp-260]
	mov	[esp],eax
	call	_fcountvertices
	sub	eax,1
	mov	[ebp-264],eax
	cmp	[ebp-264],0
	jg	_38
	sub	esp,8
	lea	eax,[ebp-252]
	mov	[esp],eax
	mov	[ebp-272],eax
	sub	esp,4
	mov	ebx,_tremove_surf
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-272]
	mov	[esp+4],ebx
	call	__bbObjStore
	mov	ebx,[ebp-256]
	mov	esi,[ebp-252]
	mov	esi,[esi]
	add	esi,0
	mov	[esi],ebx
_38
	add	[ebp-256],1
_36
	sub	esp,4
	mov	eax,[ebp-220]
	mov	eax,[eax]
	add	eax,12
	mov	eax,[eax]
	mov	[esp],eax
	call	_fcountsurfaces
	cmp	[ebp-256],eax
	jle	_37
_11
	mov	ebx,[ebp-268]
	imul	ebx,-1
	mov	[ebp-268],ebx
	sub	esp,4
	mov	eax,[ebp-220]
	mov	eax,[eax]
	add	eax,12
	mov	eax,[eax]
	mov	[esp],eax
	call	_fremovesurface
	mov	ebx,[ebp-220]
	mov	ebx,[ebx]
	add	ebx,12
	mov	[ebx],eax
	sub	esp,12
	mov	[esp+4],2
	mov	[esp+8],1
	mov	eax,[ebp-220]
	mov	eax,[eax]
	add	eax,12
	mov	eax,[eax]
	mov	[esp],eax
	call	_fentitypickmode
	sub	esp,4
	lea	eax,[ebp-220]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_34
_9
	sub	esp,4
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_ffreeentity
	mov	eax,0
	jmp	_4_leave
_4_leave
	mov	[ebp-272],eax
	sub	esp,4
	mov	ebx,[ebp-220]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjRelease
	mov	ebx,eax
	mov	eax,[ebp-272]
	mov	[ebp-272],eax
	sub	esp,4
	mov	esi,[ebp-252]
	mov	[esp],esi
	mov	eax,esi
	call	__bbObjRelease
	mov	esi,eax
	mov	eax,[ebp-272]
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 16
	.align	16
_fnearestpower
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,4
	sub	esp,4
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	__bbFAbs
	mov	ebx,[ebp+24]
	push	ebx
	fld	[esp]
	pop	ebx
	fdivp	st(1)
	push	eax
	fistp	[esp]
	pop	eax
	push	eax
	fild	[esp]
	pop	eax
	mov	ebx,[ebp+24]
	push	ebx
	fld	[esp]
	pop	ebx
	fmulp	st(1)
	mov	[ebp-4],eax
	sub	esp,4
	mov	ebx,[ebp+20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbFSgn
	mov	ebx,eax
	mov	eax,[ebp-4]
	fmulp	st(1)
	push	eax
	fistp	[esp]
	pop	eax
	jmp	_12_leave
	mov	eax,0
	jmp	_12_leave
_12_leave
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 8
	.align	16
_fupdate_clusters
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,12
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	sub	esp,8
	lea	eax,[ebp-4]
	mov	[esp],eax
	mov	[esp+4],_tcluster
	call	__bbObjEachFirst
	and	eax,eax
	jz	_14
_39
	sub	esp,8
	mov	eax,[ebp+20]
	mov	[esp],eax
	mov	ebx,[ebp-4]
	mov	ebx,[ebx]
	add	ebx,12
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	call	_fchunk_distance
	push	eax
	fild	[esp]
	pop	eax
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-8],eax
	mov	eax,[ebp-8]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,[ebp+24]
	push	ebx
	fld	[esp]
	pop	ebx
	fucompp
	fnstsw	ax
	sahf
	setb	al
	movzx	eax,al
	and	eax,eax
	jz	_40
	sub	esp,4
	mov	eax,[ebp-4]
	mov	eax,[eax]
	add	eax,12
	mov	eax,[eax]
	mov	[esp],eax
	call	_fhideentity
	jmp	_41
_40
	sub	esp,4
	mov	eax,[ebp-4]
	mov	eax,[eax]
	add	eax,12
	mov	eax,[eax]
	mov	[esp],eax
	call	_fshowentity
_41
	sub	esp,4
	lea	eax,[ebp-4]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_39
_14
	mov	eax,0
	jmp	_13_leave
_13_leave
	mov	[ebp-12],eax
	sub	esp,4
	mov	ebx,[ebp-4]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjRelease
	mov	ebx,eax
	mov	eax,[ebp-12]
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 8
	.align	16
_fchunk_distance
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,12
	mov	[ebp-4],0
	sub	esp,8
	mov	eax,[ebp+24]
	mov	[esp],eax
	mov	[esp+4],1
	call	_fgetsurface
	mov	[ebp-4],eax
	sub	esp,20
	mov	eax,[ebp+20]
	mov	[esp],eax
	mov	[esp+4],1
	call	_fentityx
	mov	[ebp-8],eax
	sub	esp,8
	mov	ebx,[ebp-4]
	mov	[esp],ebx
	mov	[esp+4],1
	mov	eax,ebx
	call	_fvertexx
	mov	ebx,eax
	mov	eax,[ebp-8]
	fsubp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp],eax
	mov	[esp+4],1073741824
	call	__bbFPow
	mov	[ebp-8],eax
	sub	esp,8
	mov	[ebp-12],eax
	sub	esp,8
	mov	ebx,[ebp+20]
	mov	[esp],ebx
	mov	[esp+4],1
	mov	eax,ebx
	call	_fentityz
	mov	ebx,eax
	mov	eax,[ebp-12]
	mov	[ebp-12],eax
	sub	esp,8
	mov	esi,[ebp-4]
	mov	[esp],esi
	mov	[esp+4],1
	mov	eax,esi
	call	_fvertexz
	mov	esi,eax
	mov	eax,[ebp-12]
	fsubp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp],ebx
	mov	[esp+4],1073741824
	mov	eax,ebx
	call	__bbFPow
	mov	ebx,eax
	mov	eax,[ebp-8]
	faddp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp],eax
	call	_fsqr
	push	eax
	fistp	[esp]
	pop	eax
	jmp	_15_leave
	mov	eax,0
	jmp	_15_leave
_15_leave
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 8
	.align	16
_fremovesurface
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,164
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	mov	[ebp-20],ebx
	mov	[ebp-24],ebx
	mov	[ebp-28],ebx
	mov	[ebp-32],ebx
	mov	[ebp-36],ebx
	mov	[ebp-40],ebx
	mov	[ebp-44],ebx
	mov	[ebp-48],ebx
	mov	[ebp-52],ebx
	mov	[ebp-56],ebx
	mov	[ebp-60],ebx
	mov	[ebp-64],ebx
	mov	[ebp-68],ebx
	mov	[ebp-72],ebx
	mov	[ebp-76],ebx
	mov	[ebp-80],ebx
	mov	[ebp-84],ebx
	mov	[ebp-88],ebx
	mov	[ebp-92],ebx
	mov	[ebp-96],ebx
	mov	[ebp-100],ebx
	mov	[ebp-104],ebx
	mov	[ebp-108],ebx
	mov	[ebp-112],ebx
	mov	[ebp-116],ebx
	mov	[ebp-120],ebx
	mov	[ebp-124],ebx
	mov	[ebp-128],ebx
	mov	[ebp-132],ebx
	mov	[ebp-136],ebx
	mov	[ebp-140],ebx
	mov	[ebp-144],ebx
	mov	[ebp-148],ebx
	mov	[ebp-152],ebx
	mov	[ebp-156],ebx
	mov	[ebp-160],ebx
	sub	esp,8
	mov	eax,_42
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	call	_fdebuglog
	sub	esp,8
	mov	eax,_43
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	call	_fdebuglog
	sub	esp,4
	mov	[esp],0
	call	_fcreatemesh
	mov	[ebp-4],eax
	sub	esp,4
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fcountsurfaces
	mov	[ebp-8],eax
	sub	esp,16
	mov	eax,[ebp-8]
	mov	[esp],eax
	call	__bbStrFromInt
	mov	[esp],eax
	mov	[ebp-164],eax
	sub	esp,4
	mov	ebx,_44
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-164]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
	mov	[ebp-12],1
	jmp	_45
_46
	mov	[ebp-16],0
	sub	esp,8
	lea	eax,[ebp-20]
	mov	[esp],eax
	mov	[esp+4],_tremove_surf
	call	__bbObjEachFirst
	and	eax,eax
	jz	_18
_47
	mov	ebx,[ebp-20]
	mov	ebx,[ebx]
	add	ebx,0
	mov	ebx,[ebx]
	cmp	[ebp-12],ebx
	jnz	_48
	mov	[ebp-16],1
_48
	sub	esp,4
	lea	eax,[ebp-20]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_47
_18
	cmp	[ebp-16],0
	jnz	_49
	sub	esp,8
	mov	eax,_50
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	call	_fdebuglog
	sub	esp,8
	mov	eax,[ebp+20]
	mov	[esp],eax
	mov	ebx,[ebp-12]
	mov	[esp+4],ebx
	call	_fgetsurface
	mov	[ebp-24],eax
	sub	esp,8
	mov	eax,[ebp-4]
	mov	[esp],eax
	mov	[esp+4],0
	call	_fcreatesurface
	mov	[ebp-28],eax
	sub	esp,4
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_fgetsurfacebrush
	mov	[ebp-32],eax
	sub	esp,4
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_fcounttriangles
	mov	[ebp-36],eax
	mov	[ebp-40],0
	jmp	_51
_52
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexred
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-44],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexgreen
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-48],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexblue
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-52],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexred
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-56],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexgreen
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-60],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexblue
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-64],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexred
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-68],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexgreen
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-72],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexblue
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-76],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexx
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-80],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexx
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-84],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexx
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-88],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexy
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-92],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexy
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-96],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexy
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-100],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexz
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-104],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexz
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-108],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexz
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-112],ebx
	sub	esp,24
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexu
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-116],ebx
	sub	esp,24
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexu
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-120],ebx
	sub	esp,24
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexu
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-124],ebx
	sub	esp,24
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexv
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-128],ebx
	sub	esp,24
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexv
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-132],ebx
	sub	esp,24
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	[esp+8],0
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexv
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-136],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexalpha
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-140],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],1
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexalpha
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-144],ebx
	sub	esp,20
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	[esp+8],2
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_ftrianglevertex
	mov	[esp+4],eax
	mov	ebx,[ebp-24]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fvertexalpha
	mov	ebx,eax
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-148],ebx
	sub	esp,28
	mov	ebx,[ebp-128]
	mov	[esp+20],ebx
	mov	[esp+24],1065353216
	mov	esi,[ebp-116]
	mov	[esp+16],esi
	mov	ebx,[ebp-104]
	mov	[esp+12],ebx
	mov	esi,[ebp-92]
	mov	[esp+8],esi
	mov	ebx,[ebp-80]
	mov	[esp+4],ebx
	mov	eax,[ebp-28]
	mov	[esp],eax
	call	_faddvertex
	mov	[ebp-152],eax
	sub	esp,28
	mov	ebx,[ebp-132]
	mov	[esp+20],ebx
	mov	[esp+24],1065353216
	mov	esi,[ebp-120]
	mov	[esp+16],esi
	mov	ebx,[ebp-108]
	mov	[esp+12],ebx
	mov	esi,[ebp-96]
	mov	[esp+8],esi
	mov	ebx,[ebp-84]
	mov	[esp+4],ebx
	mov	eax,[ebp-28]
	mov	[esp],eax
	call	_faddvertex
	mov	[ebp-156],eax
	sub	esp,28
	mov	ebx,[ebp-136]
	mov	[esp+20],ebx
	mov	[esp+24],1065353216
	mov	esi,[ebp-124]
	mov	[esp+16],esi
	mov	ebx,[ebp-112]
	mov	[esp+12],ebx
	mov	esi,[ebp-100]
	mov	[esp+8],esi
	mov	ebx,[ebp-88]
	mov	[esp+4],ebx
	mov	eax,[ebp-28]
	mov	[esp],eax
	call	_faddvertex
	mov	[ebp-160],eax
	sub	esp,16
	mov	ebx,[ebp-156]
	mov	[esp+8],ebx
	mov	esi,[ebp-160]
	mov	[esp+12],esi
	mov	esi,[ebp-152]
	mov	[esp+4],esi
	mov	eax,[ebp-28]
	mov	[esp],eax
	call	_faddtriangle
	sub	esp,24
	mov	ebx,[ebp-52]
	mov	[esp+16],ebx
	mov	esi,[ebp-140]
	mov	[esp+20],esi
	mov	esi,[ebp-48]
	mov	[esp+12],esi
	mov	ebx,[ebp-44]
	mov	[esp+8],ebx
	mov	esi,[ebp-152]
	mov	[esp+4],esi
	mov	eax,[ebp-28]
	mov	[esp],eax
	call	_fvertexcolor
	sub	esp,24
	mov	ebx,[ebp-64]
	mov	[esp+16],ebx
	mov	esi,[ebp-144]
	mov	[esp+20],esi
	mov	esi,[ebp-60]
	mov	[esp+12],esi
	mov	ebx,[ebp-56]
	mov	[esp+8],ebx
	mov	esi,[ebp-156]
	mov	[esp+4],esi
	mov	eax,[ebp-28]
	mov	[esp],eax
	call	_fvertexcolor
	sub	esp,24
	mov	ebx,[ebp-76]
	mov	[esp+16],ebx
	mov	esi,[ebp-148]
	mov	[esp+20],esi
	mov	esi,[ebp-72]
	mov	[esp+12],esi
	mov	ebx,[ebp-68]
	mov	[esp+8],ebx
	mov	esi,[ebp-160]
	mov	[esp+4],esi
	mov	eax,[ebp-28]
	mov	[esp],eax
	call	_fvertexcolor
	add	[ebp-40],1
_51
	mov	ebx,[ebp-36]
	sub	ebx,1
	cmp	[ebp-40],ebx
	jle	_52
_19
	sub	esp,8
	mov	eax,[ebp-28]
	mov	[esp],eax
	mov	ebx,[ebp-32]
	mov	[esp+4],ebx
	call	_fpaintsurface
	sub	esp,4
	mov	eax,[ebp-4]
	mov	[esp],eax
	call	_fupdatenormals
_49
	add	[ebp-12],1
_45
	mov	ebx,[ebp-8]
	cmp	[ebp-12],ebx
	jle	_46
_17
	sub	esp,4
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_ffreeentity
	mov	eax,[ebp-4]
	jmp	_16_leave
	mov	eax,0
	jmp	_16_leave
_16_leave
	mov	[ebp-164],eax
	sub	esp,4
	mov	ebx,[ebp-20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjRelease
	mov	ebx,eax
	mov	eax,[ebp-164]
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 4
	.align	4
_tremove_surf	.dd	5
_20	.dd	0
	.dd	_20
	.dd	_20
	.dd	0
	.dd	-1
_21	.dd	0
	.dd	_21
	.dd	_21
	.dd	0
	.dd	-1
	.dd	1
	.dd	__bbIntType
	.align	4
_3	.dd	6
	.dd	201
	.dd	__bbIntType
	.align	4
_tcluster	.dd	5
_22	.dd	0
	.dd	_22
	.dd	_22
	.dd	0
	.dd	-1
_23	.dd	0
	.dd	_23
	.dd	_23
	.dd	0
	.dd	-1
	.dd	5
	.dd	__bbFltType
	.dd	__bbFltType
	.dd	__bbFltType
	.dd	__bbIntType
	.dd	_3
_42	.db	"testing removal",0
_43	.db	"creating mesh target",0
_44	.db	" original surfaces",0
_50	.db	"making surf",0
	.align	4
__LIBS
	.db	"",0
	.align	4
__DATA
	.dd	0

