
	.align	16
__MAIN
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,24
	sub	esp,4
	mov	eax,__DATA
	mov	[esp],eax
	call	__bbRestore
	sub	esp,4
	mov	eax,__LIBS
	mov	[esp],eax
	call	__bbLoadLibs
	call	_2_begin
	jmp	_2_leave
_2_begin
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	sub	esp,16
	mov	[esp+8],32
	mov	[esp+12],2
	mov	[esp+4],480
	mov	[esp],640
	call	_fgraphics3d
	sub	esp,4
	call	_fbackbuffer
	mov	[esp],eax
	call	_fsetbuffer
	sub	esp,4
	mov	[esp],0
	call	_fcreatecamera
	mov	[_vcamera],eax
	sub	esp,16
	mov	[esp+8],1077936128
	mov	[esp+12],0
	mov	[esp+4],1077936128
	mov	eax,[_vcamera]
	mov	[esp],eax
	call	_fmoveentity
	sub	esp,20
	mov	[esp+12],0
	mov	[esp+16],0
	mov	[esp+8],1106247680
	mov	[esp+4],1106247680
	mov	eax,[_vcamera]
	mov	[esp],eax
	call	_frotateentity
	sub	esp,8
	mov	[esp],1
	mov	[esp+4],0
	call	_fcreatelight
	mov	[ebp-4],eax
	sub	esp,4
	mov	[esp],0
	call	_fcreatecube
	mov	[_vcube],eax
	sub	esp,20
	mov	[esp+12],1084227584
	mov	[esp+16],0
	mov	[esp+8],0
	mov	[esp+4],0
	mov	eax,[_vcube]
	mov	[esp],eax
	call	_fpositionentity
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],1
	mov	[esp+4],300
	mov	[esp],300
	call	_fcreatetexture
	mov	[ebp-8],eax
	sub	esp,12
	mov	eax,[ebp-8]
	mov	[esp],eax
	mov	[esp+4],0
	call	_ftexturebuffer
	mov	[esp],eax
	call	_fsetbuffer
	sub	esp,12
	mov	[esp+4],255
	mov	[esp+8],255
	mov	[esp],255
	call	_fclscolor
	call	_fcls
	sub	esp,4
	call	_fmillisecs
	mov	[esp],eax
	call	_fseedrnd
	mov	[ebp-12],1
	jmp	_5
_6
	sub	esp,20
	mov	[esp],256
	mov	[esp+4],1
	call	_frand
	mov	[esp+4],eax
	mov	[ebp-20],eax
	sub	esp,8
	mov	[esp],256
	mov	[esp+4],1
	mov	eax,ebx
	call	_frand
	mov	ebx,eax
	mov	eax,[ebp-20]
	mov	[esp+8],ebx
	mov	[ebp-20],eax
	sub	esp,8
	mov	[esp],256
	mov	[esp+4],1
	mov	eax,ebx
	call	_frand
	mov	ebx,eax
	mov	eax,[ebp-20]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fcolor
	mov	ebx,eax
	sub	esp,28
	mov	[esp],600
	mov	[esp+4],1
	call	_frand
	mov	[esp+8],eax
	mov	[ebp-20],eax
	sub	esp,8
	mov	[esp],600
	mov	[esp+4],1
	mov	eax,ebx
	call	_frand
	mov	ebx,eax
	mov	eax,[ebp-20]
	mov	[esp+12],ebx
	mov	[esp+16],1
	mov	[ebp-20],eax
	sub	esp,8
	mov	[esp],600
	mov	[esp+4],1
	mov	eax,ebx
	call	_frand
	mov	ebx,eax
	mov	eax,[ebp-20]
	mov	[esp+4],ebx
	sub	esp,8
	mov	[esp],600
	mov	[esp+4],1
	call	_frand
	mov	[esp],eax
	call	_frect
	add	[ebp-12],1
_5
	cmp	[ebp-12],50
	jle	_6
_3
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],0
	mov	esi,[ebp-8]
	mov	[esp+4],esi
	mov	eax,[_vcube]
	mov	[esp],eax
	call	_fentitytexture
	sub	esp,4
	call	_fbackbuffer
	mov	[esp],eax
	call	_fsetbuffer
	mov	[ebp-16],1
	mov	eax,640
	mov	ecx,[ebp-16]
	cdq
	idiv	ecx
	mov	[_vsizex],eax
	mov	eax,480
	mov	ecx,[ebp-16]
	cdq
	idiv	ecx
	mov	[_vsizey],eax
	sub	esp,16
	mov	[esp+8],256
	mov	[esp+12],1
	mov	[esp+4],384
	mov	[esp],384
	call	_fcreatetexture
	mov	[_vglowtexture],eax
	sub	esp,4
	mov	eax,[_vcamera]
	mov	[esp],eax
	call	_fcreatesprite
	mov	[_vsp],eax
	sub	esp,16
	mov	[esp+8],-1116355953
	mov	[esp+12],1066863165
	mov	[esp+4],-1098907648
	mov	eax,[_vsp]
	mov	[esp],eax
	call	_fmoveentity
	sub	esp,8
	mov	eax,[_vsp]
	mov	[esp],eax
	mov	[esp+4],1050924810
	call	_fentityalpha
	sub	esp,12
	call	_fgraphicswidth
	mov	ecx,[_vsizex]
	cdq
	idiv	ecx
	push	eax
	fild	[esp]
	pop	eax
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp+4],eax
	mov	[ebp-20],eax
	mov	[ebp-24],eax
	mov	eax,ebx
	call	_fgraphicsheight
	mov	ebx,eax
	mov	eax,[ebp-24]
	mov	ecx,[_vsizey]
	mov	eax,ebx
	cdq
	idiv	ecx
	mov	ebx,eax
	mov	eax,[ebp-20]
	push	ebx
	fild	[esp]
	pop	ebx
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+8],ebx
	mov	ebx,[_vglowtexture]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fscaletexture
	mov	ebx,eax
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],0
	mov	esi,[_vglowtexture]
	mov	[esp+4],esi
	mov	eax,[_vsp]
	mov	[esp],eax
	call	_fentitytexture
	sub	esp,8
	mov	eax,[_vglowtexture]
	mov	[esp],eax
	mov	[esp+4],5
	call	_ftextureblend
	jmp	_8
_7
	sub	esp,20
	mov	[esp+12],1056964608
	mov	[esp+16],0
	mov	[esp+8],1056964608
	mov	[esp+4],1056964608
	mov	eax,[_vcube]
	mov	[esp],eax
	call	_fturnentity
	sub	esp,20
	mov	ebx,[_vsizex]
	mov	[esp+12],ebx
	mov	esi,[_vsizey]
	mov	[esp+16],esi
	mov	[esp+8],0
	mov	[esp+4],0
	mov	eax,[_vcamera]
	mov	[esp],eax
	call	_fcameraviewport
	sub	esp,4
	mov	[esp],1065353216
	call	_frenderworld
	sub	esp,40
	mov	eax,[_vglowtexture]
	mov	[esp],eax
	mov	[esp+4],0
	call	_ftexturebuffer
	mov	[esp+28],eax
	mov	[ebp-20],eax
	mov	eax,ebx
	call	_fbackbuffer
	mov	ebx,eax
	mov	eax,[ebp-20]
	mov	[esp+24],ebx
	mov	[esp+20],0
	mov	[esp+16],0
	mov	esi,[_vsizey]
	mov	[esp+12],esi
	mov	ebx,[_vsizex]
	mov	[esp+8],ebx
	mov	[esp+4],0
	mov	[esp],0
	call	_fcopyrect
	sub	esp,20
	call	_fgraphicswidth
	mov	[esp+12],eax
	mov	[ebp-20],eax
	mov	eax,ebx
	call	_fgraphicsheight
	mov	ebx,eax
	mov	eax,[ebp-20]
	mov	[esp+16],ebx
	mov	[esp+8],0
	mov	[esp+4],0
	mov	eax,[_vcamera]
	mov	[esp],eax
	call	_fcameraviewport
	sub	esp,4
	mov	[esp],1065353216
	call	_frenderworld
	sub	esp,4
	mov	[esp],1
	call	_fflip
_8
	sub	esp,4
	mov	[esp],1
	call	_fkeydown
	cmp	eax,0
	jz	_7
_4
	call	_fend
	ret
_2_leave
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 0
	.align	4
_vcamera	.dd	0
	.align	4
_vcube	.dd	0
	.align	4
_vsizex	.dd	0
	.align	4
_vsizey	.dd	0
	.align	4
_vglowtexture	.dd	0
	.align	4
_vsp	.dd	0
	.align	4
__LIBS
	.db	"",0
	.align	4
__DATA
	.dd	0

