
	.align	16
__MAIN
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,32
	sub	esp,4
	mov	eax,__DATA
	mov	[esp],eax
	call	__bbRestore
	sub	esp,4
	mov	eax,__LIBS
	mov	[esp],eax
	call	__bbLoadLibs
	call	_2_begin
	jmp	_2_leave
_2_begin
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	mov	[ebp-20],ebx
	mov	[ebp-24],ebx
	mov	[ebp-28],ebx
	sub	esp,4
	mov	eax,_acamera
	mov	[esp],eax
	call	__bbUndimArray
	mov	ebx,0
	mov	esi,_acamera
	add	esi,12
	mov	[esi],ebx
	sub	esp,4
	mov	eax,_acamera
	mov	[esp],eax
	call	__bbDimArray
	sub	esp,4
	mov	eax,_atimer
	mov	[esp],eax
	call	__bbUndimArray
	mov	ebx,0
	mov	esi,_atimer
	add	esi,12
	mov	[esi],ebx
	sub	esp,4
	mov	eax,_atimer
	mov	[esp],eax
	call	__bbDimArray
	sub	esp,4
	mov	eax,_aold_mousex
	mov	[esp],eax
	call	__bbUndimArray
	mov	ebx,0
	mov	esi,_aold_mousex
	add	esi,12
	mov	[esi],ebx
	sub	esp,4
	mov	eax,_aold_mousex
	mov	[esp],eax
	call	__bbDimArray
	sub	esp,4
	mov	eax,_aold_mousey
	mov	[esp],eax
	call	__bbUndimArray
	mov	ebx,0
	mov	esi,_aold_mousey
	add	esi,12
	mov	[esi],ebx
	sub	esp,4
	mov	eax,_aold_mousey
	mov	[esp],eax
	call	__bbDimArray
	sub	esp,16
	mov	[esp+8],32
	mov	[esp+12],3
	mov	[esp+4],600
	mov	[esp],800
	call	_fgraphics3d
	sub	esp,4
	call	_fbackbuffer
	mov	[esp],eax
	call	_fsetbuffer
	call	_fcleartexturefilters
	sub	esp,4
	mov	[esp],0
	call	_fcreatecamera
	mov	ebx,0
	shl	ebx,byte 2
	add	ebx,[_acamera]
	mov	[ebx],eax
	sub	esp,8
	mov	[esp],1
	mov	[esp+4],0
	call	_fcreatelight
	mov	[ebp-4],eax
	sub	esp,20
	mov	[esp+12],0
	mov	[esp+16],0
	mov	[esp+8],1112014848
	mov	[esp+4],0
	mov	eax,[ebp-4]
	mov	[esp],eax
	call	_fpositionentity
	sub	esp,4
	mov	[esp],30
	call	_fcreatetimer
	mov	ebx,0
	shl	ebx,byte 2
	add	ebx,[_atimer]
	mov	[ebx],eax
	sub	esp,20
	mov	[esp+12],1084227584
	mov	[esp+16],0
	mov	[esp+8],1084227584
	mov	[esp+4],1084227584
	mov	eax,0
	shl	eax,byte 2
	add	eax,[_acamera]
	mov	eax,[eax]
	mov	[esp],eax
	call	_fpositionentity
	sub	esp,16
	mov	[esp+8],256
	mov	[esp+12],1
	mov	[esp+4],512
	mov	[esp],512
	call	_fcreatetexture
	mov	[ebp-8],eax
	sub	esp,4
	mov	[esp],0
	call	_fcreatecube
	mov	[ebp-12],eax
	sub	esp,12
	mov	ebx,[ebp-12]
	mov	[esp+4],ebx
	mov	[esp+8],0
	mov	eax,0
	shl	eax,byte 2
	add	eax,[_acamera]
	mov	eax,[eax]
	mov	[esp],eax
	call	_fpointentity
	jmp	_6
_5
	call	_fmillisecs
	mov	[ebp-16],eax
	sub	esp,4
	mov	[esp],57
	call	_fkeydown
	mov	[ebp-32],eax
	cmp	[ebp-20],0
	mov	eax,ebx
	setz	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-32]
	and	eax,ebx
	and	eax,eax
	jz	_7
	mov	[ebp-20],1
	sub	esp,8
	mov	eax,_8
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	call	_fopenmovie
	mov	[ebp-24],eax
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],0
	mov	esi,[ebp-8]
	mov	[esp+4],esi
	mov	eax,[ebp-12]
	mov	[esp],eax
	call	_fentitytexture
	sub	esp,4
	mov	eax,[ebp-12]
	mov	[esp],eax
	call	_fshowentity
_7
	cmp	[ebp-24],0
	jle	_9
	sub	esp,20
	mov	[esp+12],512
	mov	[esp+16],512
	mov	[esp+8],0
	mov	[esp+4],0
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_fdrawmovie
	sub	esp,4
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_fmovieplaying
	cmp	eax,0
	jnz	_10
	sub	esp,4
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_fclosemovie
	mov	[ebp-24],0
	mov	[ebp-20],0
	sub	esp,4
	mov	eax,[ebp-12]
	mov	[esp],eax
	call	_fhideentity
_10
_9
	sub	esp,40
	mov	eax,[ebp-8]
	mov	[esp],eax
	mov	[esp+4],0
	call	_ftexturebuffer
	mov	[esp+28],eax
	mov	[ebp-32],eax
	mov	eax,ebx
	call	_fbackbuffer
	mov	ebx,eax
	mov	eax,[ebp-32]
	mov	[esp+24],ebx
	mov	[esp+20],0
	mov	[esp+16],0
	mov	[esp+12],512
	mov	[esp+8],512
	mov	[esp+4],0
	mov	[esp],0
	call	_fcopyrect
	call	_fmillisecs
	sub	eax,[ebp-16]
	mov	[ebp-28],eax
	call	_fgestione_camera_editor
	sub	esp,4
	mov	[esp],1065353216
	call	_frenderworld
	call	_fmousex
	mov	ebx,0
	shl	ebx,byte 2
	add	ebx,[_aold_mousex]
	mov	[ebx],eax
	call	_fmousey
	mov	ebx,0
	shl	ebx,byte 2
	add	ebx,[_aold_mousey]
	mov	[ebx],eax
	sub	esp,4
	mov	[esp],0
	call	_fflip
	sub	esp,4
	mov	eax,0
	shl	eax,byte 2
	add	eax,[_atimer]
	mov	eax,[eax]
	mov	[esp],eax
	call	_fwaittimer
_6
	sub	esp,4
	mov	[esp],1
	call	_fkeydown
	cmp	eax,0
	jz	_5
_3
	call	_fend
	ret
_2_leave
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 0
	.align	16
_fgestione_camera_editor
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,20
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	mov	ebx,0
	shl	ebx,byte 2
	add	ebx,[_aold_mousex]
	mov	ebx,[ebx]
	call	_fmousex
	sub	ebx,eax
	push	ebx
	fild	[esp]
	pop	ebx
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-4],ebx
	mov	ebx,0
	shl	ebx,byte 2
	add	ebx,[_aold_mousey]
	mov	ebx,[ebx]
	call	_fmousey
	sub	ebx,eax
	push	ebx
	fild	[esp]
	pop	ebx
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],1065353216
	sub	esp,20
	mov	[esp],205
	call	_fkeydown
	mov	[ebp-20],eax
	sub	esp,4
	mov	[esp],203
	mov	eax,ebx
	call	_fkeydown
	mov	ebx,eax
	mov	eax,[ebp-20]
	sub	eax,ebx
	push	eax
	fild	[esp]
	pop	eax
	mov	ebx,[ebp-12]
	push	ebx
	fld	[esp]
	pop	ebx
	fmulp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp+4],eax
	mov	[ebp-20],eax
	sub	esp,4
	mov	[esp],200
	mov	eax,ebx
	call	_fkeydown
	mov	ebx,eax
	mov	eax,[ebp-20]
	mov	[ebp-20],eax
	sub	esp,4
	mov	[esp],208
	mov	eax,esi
	call	_fkeydown
	mov	esi,eax
	mov	eax,[ebp-20]
	sub	ebx,esi
	push	ebx
	fild	[esp]
	pop	ebx
	mov	esi,[ebp-12]
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+12],ebx
	mov	[esp+8],0
	mov	ebx,0
	shl	ebx,byte 2
	add	ebx,[_acamera]
	mov	ebx,[ebx]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fmoveentity
	mov	ebx,eax
	sub	esp,4
	mov	[esp],2
	call	_fmousedown
	and	eax,eax
	jz	_11
	mov	[ebp-16],1061997773
	sub	esp,20
	mov	ebx,[ebp-8]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-16]
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+4],ebx
	mov	[esp+12],0
	mov	[esp+16],0
	mov	[esp+8],0
	mov	eax,0
	shl	eax,byte 2
	add	eax,[_acamera]
	mov	eax,[eax]
	mov	[esp],eax
	call	_fturnentity
	sub	esp,20
	mov	ebx,[ebp-4]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-16]
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+8],ebx
	mov	[esp+12],0
	mov	[esp+16],1
	mov	[esp+4],0
	mov	eax,0
	shl	eax,byte 2
	add	eax,[_acamera]
	mov	eax,[eax]
	mov	[esp],eax
	call	_fturnentity
_11
	mov	eax,0
	jmp	_4_leave
_4_leave
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 0
	.align	4
_acamera	.dd	0
	.dd	1
	.dd	1
	.dd	0
	.align	4
_atimer	.dd	0
	.dd	1
	.dd	1
	.dd	0
	.align	4
_aold_mousex	.dd	0
	.dd	1
	.dd	1
	.dd	0
	.align	4
_aold_mousey	.dd	0
	.dd	1
	.dd	1
	.dd	0
_8	.db	"avi/Seq_04.avi",0
	.align	4
__LIBS
	.db	"",0
	.align	4
__DATA
	.dd	0

