
	.align	16
__MAIN
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,4
	sub	esp,4
	mov	eax,__DATA
	mov	[esp],eax
	call	__bbRestore
	sub	esp,4
	mov	eax,__LIBS
	mov	[esp],eax
	call	__bbLoadLibs
	call	_2_begin
	jmp	_2_leave
_2_begin
	sub	esp,4
	mov	eax,_6
	mov	[esp],eax
	call	__bbVecAlloc
	mov	[_varray_line_elements],eax
	mov	[ebp-4],eax
	sub	esp,4
	mov	ebx,_7
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbVecAlloc
	mov	ebx,eax
	mov	eax,[ebp-4]
	mov	[_varray_vertex],ebx
	mov	[ebp-4],eax
	sub	esp,4
	mov	ebx,_8
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbVecAlloc
	mov	ebx,eax
	mov	eax,[ebp-4]
	mov	[_varray_normal],ebx
	mov	[ebp-4],eax
	sub	esp,4
	mov	ebx,_9
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbVecAlloc
	mov	ebx,eax
	mov	eax,[ebp-4]
	mov	[_varray_uvw],ebx
	mov	[ebp-4],eax
	sub	esp,4
	mov	ebx,_10
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbVecAlloc
	mov	ebx,eax
	mov	eax,[ebp-4]
	mov	[_varray_face],ebx
	mov	[ebp-4],eax
	sub	esp,4
	mov	ebx,_11
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbVecAlloc
	mov	ebx,eax
	mov	eax,[ebp-4]
	mov	[_varray_surface],ebx
	mov	[ebp-4],eax
	sub	esp,4
	mov	ebx,_12
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbVecAlloc
	mov	ebx,eax
	mov	eax,[ebp-4]
	mov	[_varray_material],ebx
	mov	[ebp-4],eax
	sub	esp,4
	mov	ebx,_13
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbVecAlloc
	mov	ebx,eax
	mov	eax,[ebp-4]
	mov	[_varray_dummy_face],ebx
	ret
_2_leave
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 0
	.align	16
_ffunc_import_silo_obj
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,224
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	mov	[ebp-20],ebx
	mov	[ebp-24],ebx
	mov	[ebp-28],ebx
	mov	[ebp-32],ebx
	mov	[ebp-36],ebx
	mov	[ebp-40],ebx
	mov	[ebp-44],ebx
	mov	[ebp-48],ebx
	mov	[ebp-52],ebx
	mov	[ebp-56],ebx
	mov	[ebp-60],ebx
	mov	[ebp-64],ebx
	mov	[ebp-68],ebx
	mov	[ebp-72],ebx
	mov	[ebp-76],ebx
	mov	[ebp-80],ebx
	mov	[ebp-84],ebx
	mov	[ebp-88],ebx
	mov	[ebp-92],ebx
	mov	[ebp-96],ebx
	mov	[ebp-100],ebx
	mov	[ebp-104],ebx
	mov	[ebp-108],ebx
	mov	[ebp-112],ebx
	mov	[ebp-116],ebx
	mov	[ebp-120],ebx
	mov	[ebp-124],ebx
	mov	[ebp-128],ebx
	mov	[ebp-132],ebx
	mov	[ebp-136],ebx
	mov	[ebp-140],ebx
	mov	[ebp-144],ebx
	mov	[ebp-148],ebx
	mov	[ebp-152],ebx
	mov	[ebp-156],ebx
	mov	[ebp-160],ebx
	mov	[ebp-164],ebx
	mov	[ebp-168],ebx
	mov	[ebp-172],ebx
	mov	[ebp-176],ebx
	mov	[ebp-180],ebx
	mov	[ebp-184],ebx
	mov	[ebp-188],ebx
	mov	[ebp-192],ebx
	mov	[ebp-196],ebx
	mov	[ebp-200],ebx
	mov	[ebp-204],ebx
	mov	[ebp-208],ebx
	mov	[ebp-212],ebx
	mov	[ebp-4],0
	sub	esp,8
	lea	eax,[ebp-8]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_57
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,8
	lea	eax,[ebp-12]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_58
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,8
	lea	eax,[ebp-16]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_59
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	mov	[ebp-20],1
	mov	[ebp-24],1
	mov	[ebp-28],1
	mov	[ebp-32],1
	mov	[ebp-36],1
	mov	[ebp-40],1
	sub	esp,8
	lea	eax,[ebp+20]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	_flen
	mov	[ebp-44],eax
_60
	sub	esp,20
	mov	ebx,[ebp-44]
	mov	[esp+4],ebx
	mov	[esp+8],1
	sub	esp,4
	lea	eax,[ebp+20]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	_fmid
	mov	[esp+4],eax
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
	sub	[ebp-44],1
	sub	esp,12
	lea	eax,[ebp-48]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_61
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	setz	al
	movzx	eax,al
	mov	[ebp-216],eax
	cmp	[ebp-44],0
	mov	eax,ebx
	setz	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-216]
	or	ebx,eax
	and	ebx,ebx
	jz	_60
_15
	cmp	[ebp-44],0
	jle	_62
	sub	esp,20
	lea	eax,[ebp+20]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	[ebp-220],eax
	sub	esp,4
	lea	ebx,[ebp+20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-220]
	mov	[esp],ebx
	mov	eax,ebx
	call	_flen
	mov	ebx,eax
	mov	eax,[ebp-216]
	sub	ebx,[ebp-44]
	sub	ebx,1
	mov	[esp+4],ebx
	call	_fright
	mov	[esp+4],eax
	lea	ebx,[ebp-52]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
	sub	esp,20
	lea	eax,[ebp+20]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	ebx,[ebp-44]
	add	ebx,1
	mov	[esp+4],ebx
	call	_fleft
	mov	[esp+4],eax
	lea	ebx,[ebp-56]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
	jmp	_63
_62
	sub	esp,8
	lea	eax,[ebp-52]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp+20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,8
	lea	eax,[ebp-56]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_64
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
_63
	sub	esp,8
	lea	eax,[ebp+20]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	_fopenfile
	mov	[ebp-60],eax
	mov	ebx,[ebp-60]
	and	ebx,ebx
	jz	_65
	sub	esp,24
	mov	eax,_66
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp+20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_67
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
	sub	esp,4
	mov	[esp],0
	call	_fcreatemesh
	mov	[ebp-4],eax
	sub	esp,20
	mov	[esp+12],0
	mov	[esp+16],0
	mov	[esp+8],0
	mov	[esp+4],0
	mov	eax,[ebp-4]
	mov	[esp],eax
	call	_fpositionentity
	sub	esp,20
	mov	[esp+12],0
	mov	[esp+16],0
	mov	[esp+8],0
	mov	[esp+4],0
	mov	eax,[ebp-4]
	mov	[esp],eax
	call	_frotateentity
	sub	esp,8
	mov	eax,[ebp-60]
	mov	[esp],eax
	mov	[esp+4],0
	call	_fseekfile
	mov	[ebp-64],0
_68
	sub	esp,8
	lea	eax,[ebp-68]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-60]
	mov	[esp],ebx
	mov	eax,ebx
	call	_freadline
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,12
	lea	eax,[ebp-68]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_69
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	_ffunc_parse_line
	sub	esp,8
	lea	eax,[ebp-72]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,4
	add	ebx,[_varray_line_elements]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,12
	lea	eax,[ebp-72]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_72
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_71
	sub	esp,12
	lea	eax,[ebp-72]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_74
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_73
	sub	esp,12
	lea	eax,[ebp-72]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_76
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_75
	sub	esp,12
	lea	eax,[ebp-72]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_78
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_77
	sub	esp,12
	lea	eax,[ebp-72]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_80
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_79
	sub	esp,12
	lea	eax,[ebp-72]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_82
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_81
	sub	esp,12
	lea	eax,[ebp-72]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_84
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_83
	sub	esp,12
	lea	eax,[ebp-72]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_86
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_85
	sub	esp,12
	lea	eax,[ebp-72]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_88
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_87
	sub	esp,16
	mov	eax,_89
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-68]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
	jmp	_70
_71
	jmp	_70
_73
	sub	esp,8
	lea	eax,[ebp-8]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,8
	add	ebx,[_varray_line_elements]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	jmp	_70
_75
	sub	esp,8
	lea	eax,[ebp-12]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,8
	add	ebx,[_varray_line_elements]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	jmp	_70
_77
	sub	esp,8
	mov	eax,[ebp-20]
	shl	eax,byte 2
	add	eax,[_varray_vertex]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_ttype_vertex
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbObjStore
	mov	ebx,[ebp-20]
	mov	esi,[ebp-20]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,0
	mov	[esi],ebx
	sub	esp,8
	mov	eax,8
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	fchs
	push	eax
	fstp	[esp]
	pop	eax
	mov	ebx,[ebp-20]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	[ebx],eax
	sub	esp,8
	mov	eax,12
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	push	eax
	fstp	[esp]
	pop	eax
	mov	ebx,[ebp-20]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,12
	mov	[ebx],eax
	sub	esp,8
	mov	eax,16
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	push	eax
	fstp	[esp]
	pop	eax
	mov	ebx,[ebp-20]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	[ebx],eax
	mov	ebx,-1
	mov	esi,[ebp-20]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	[esi],ebx
	add	[ebp-20],1
	jmp	_70
_79
	sub	esp,8
	mov	eax,[ebp-24]
	shl	eax,byte 2
	add	eax,[_varray_normal]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_ttype_normal
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbObjStore
	mov	ebx,[ebp-24]
	mov	esi,[ebp-24]
	shl	esi,byte 2
	add	esi,[_varray_normal]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,0
	mov	[esi],ebx
	sub	esp,8
	mov	eax,8
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	fchs
	push	eax
	fstp	[esp]
	pop	eax
	mov	ebx,[ebp-24]
	shl	ebx,byte 2
	add	ebx,[_varray_normal]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	[ebx],eax
	sub	esp,8
	mov	eax,12
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	push	eax
	fstp	[esp]
	pop	eax
	mov	ebx,[ebp-24]
	shl	ebx,byte 2
	add	ebx,[_varray_normal]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	[ebx],eax
	sub	esp,8
	mov	eax,16
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	push	eax
	fstp	[esp]
	pop	eax
	mov	ebx,[ebp-24]
	shl	ebx,byte 2
	add	ebx,[_varray_normal]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,12
	mov	[ebx],eax
	add	[ebp-24],1
	jmp	_70
_81
	sub	esp,8
	mov	eax,[ebp-28]
	shl	eax,byte 2
	add	eax,[_varray_uvw]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_ttype_uvw
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbObjStore
	mov	ebx,[ebp-28]
	mov	esi,[ebp-28]
	shl	esi,byte 2
	add	esi,[_varray_uvw]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,0
	mov	[esi],ebx
	sub	esp,8
	mov	eax,8
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	push	eax
	fstp	[esp]
	pop	eax
	mov	ebx,[ebp-28]
	shl	ebx,byte 2
	add	ebx,[_varray_uvw]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	[ebx],eax
	sub	esp,8
	mov	eax,12
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	fchs
	push	eax
	fstp	[esp]
	pop	eax
	mov	ebx,[ebp-28]
	shl	ebx,byte 2
	add	ebx,[_varray_uvw]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	[ebx],eax
	add	[ebp-28],1
	jmp	_70
_83
	sub	esp,8
	lea	eax,[ebp-76]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,8
	add	ebx,[_varray_line_elements]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,12
	lea	eax,[ebp-76]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_91
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jnz	_90
	mov	[ebp-64],1
	sub	esp,8
	mov	[esp],4
	mov	ebx,[ebp-4]
	mov	[esp+4],ebx
	call	_fcreatesphere
	mov	[ebp-80],eax
	sub	esp,16
	mov	[esp+8],1028443341
	mov	[esp+12],1028443341
	mov	[esp+4],1028443341
	mov	eax,[ebp-80]
	mov	[esp],eax
	call	_fscalemesh
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],0
	mov	[esp+4],1132396544
	mov	eax,[ebp-80]
	mov	[esp],eax
	call	_fentitycolor
	sub	esp,8
	mov	eax,[ebp-80]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,12
	add	ebx,[_varray_line_elements]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	_fnameentity
	sub	esp,24
	mov	eax,_92
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-80]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fentityname
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_93
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
	jmp	_94
_90
	mov	[ebp-64],0
_94
	jmp	_70
_85
	cmp	[ebp-64],0
	jnz	_95
	sub	esp,8
	lea	eax,[ebp-84]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,8
	add	ebx,[_varray_line_elements]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	mov	[ebp-44],1
_96
	sub	esp,20
	mov	ebx,[ebp-44]
	mov	[esp+4],ebx
	mov	[esp+8],1
	sub	esp,4
	lea	eax,[ebp-84]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	_fmid
	mov	[esp+4],eax
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
	add	[ebp-44],1
	sub	esp,12
	lea	eax,[ebp-48]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_97
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	setz	al
	movzx	eax,al
	mov	[ebp-216],eax
	mov	[ebp-220],eax
	sub	esp,4
	mov	[ebp-224],eax
	sub	esp,4
	lea	ebx,[ebp-84]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-224]
	mov	[esp],ebx
	mov	eax,ebx
	call	_flen
	mov	ebx,eax
	mov	eax,[ebp-220]
	cmp	[ebp-44],ebx
	mov	eax,ebx
	setg	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-216]
	or	eax,ebx
	and	eax,eax
	jz	_96
_18
	sub	esp,20
	lea	eax,[ebp-84]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	ebx,[ebp-44]
	sub	ebx,2
	mov	[esp+4],ebx
	call	_fleft
	mov	[esp+4],eax
	lea	ebx,[ebp-16]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
_95
	jmp	_70
_87
	cmp	[ebp-64],0
	jnz	_98
	sub	esp,8
	mov	eax,[ebp-32]
	shl	eax,byte 2
	add	eax,[_varray_face]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_ttype_face
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbObjStore
	mov	ebx,[ebp-32]
	mov	esi,[ebp-32]
	shl	esi,byte 2
	add	esi,[_varray_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,0
	mov	[esi],ebx
	sub	esp,8
	mov	eax,[ebp-32]
	shl	eax,byte 2
	add	eax,[_varray_face]
	mov	eax,[eax]
	mov	eax,[eax]
	add	eax,8
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-16]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	mov	[ebp-88],2
	mov	[ebp-92],1
	jmp	_100
_99
	mov	[ebp-44],1
	sub	esp,8
	lea	eax,[ebp-48]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_101
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,8
	lea	eax,[ebp-96]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_102
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
_103
	sub	esp,20
	mov	ebx,[ebp-44]
	mov	[esp+4],ebx
	mov	[esp+8],1
	sub	esp,4
	mov	eax,[ebp-88]
	shl	eax,byte 2
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	_fmid
	mov	[esp+4],eax
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
	sub	esp,12
	lea	eax,[ebp-48]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_105
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_104
	sub	esp,20
	lea	eax,[ebp-96]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp+4],eax
	lea	ebx,[ebp-96]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
_104
	add	[ebp-44],1
	sub	esp,12
	lea	eax,[ebp-48]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_106
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jnz	_103
_20
	mov	ebx,[ebp-88]
	sub	ebx,1
	shl	ebx,byte 2
	mov	esi,[ebp-32]
	shl	esi,byte 2
	add	esi,[_varray_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,16
	mov	esi,[esi]
	add	ebx,esi
	sub	esp,8
	lea	eax,[ebp-96]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToInt
	mov	[ebx],eax
	sub	esp,8
	lea	eax,[ebp-48]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_107
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,8
	lea	eax,[ebp-96]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_108
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
_109
	sub	esp,20
	mov	ebx,[ebp-44]
	mov	[esp+4],ebx
	mov	[esp+8],1
	sub	esp,4
	mov	eax,[ebp-88]
	shl	eax,byte 2
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	_fmid
	mov	[esp+4],eax
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
	sub	esp,12
	lea	eax,[ebp-48]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_111
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_110
	sub	esp,20
	lea	eax,[ebp-96]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp+4],eax
	lea	ebx,[ebp-96]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
_110
	add	[ebp-44],1
	sub	esp,12
	lea	eax,[ebp-48]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_112
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jnz	_109
_21
	mov	ebx,[ebp-88]
	sub	ebx,1
	shl	ebx,byte 2
	mov	esi,[ebp-32]
	shl	esi,byte 2
	add	esi,[_varray_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,24
	mov	esi,[esi]
	add	ebx,esi
	sub	esp,8
	lea	eax,[ebp-96]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToInt
	mov	[ebx],eax
	sub	esp,8
	lea	eax,[ebp-48]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_113
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,8
	lea	eax,[ebp-96]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_114
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
_115
	sub	esp,20
	mov	ebx,[ebp-44]
	mov	[esp+4],ebx
	mov	[esp+8],1
	sub	esp,4
	mov	eax,[ebp-88]
	shl	eax,byte 2
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	_fmid
	mov	[esp+4],eax
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
	sub	esp,12
	lea	eax,[ebp-48]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_117
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_116
	sub	esp,20
	lea	eax,[ebp-96]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp+4],eax
	lea	ebx,[ebp-96]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
_116
	add	[ebp-44],1
	sub	esp,12
	lea	eax,[ebp-48]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_118
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	setz	al
	movzx	eax,al
	mov	[ebp-216],eax
	mov	[ebp-220],eax
	sub	esp,8
	mov	[ebp-224],eax
	sub	esp,4
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-224]
	mov	[esp],ebx
	mov	[ebp-224],eax
	sub	esp,4
	mov	esi,_119
	mov	[esp],esi
	mov	eax,esi
	call	__bbStrConst
	mov	esi,eax
	mov	eax,[ebp-224]
	mov	[esp+4],esi
	mov	eax,ebx
	call	__bbStrCompare
	mov	ebx,eax
	mov	eax,[ebp-220]
	cmp	ebx,0
	mov	eax,ebx
	setz	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-216]
	or	eax,ebx
	and	eax,eax
	jz	_115
_22
	mov	ebx,[ebp-88]
	sub	ebx,1
	shl	ebx,byte 2
	mov	esi,[ebp-32]
	shl	esi,byte 2
	add	esi,[_varray_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,20
	mov	esi,[esi]
	add	ebx,esi
	sub	esp,8
	lea	eax,[ebp-96]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToInt
	mov	[ebx],eax
	add	[ebp-88],1
_100
	sub	esp,12
	mov	eax,[ebp-88]
	shl	eax,byte 2
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_120
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jnz	_99
_19
	mov	ebx,[ebp-88]
	sub	ebx,2
	mov	esi,[ebp-32]
	shl	esi,byte 2
	add	esi,[_varray_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,12
	mov	[esi],ebx
	add	[ebp-32],1
	jmp	_121
_98
	sub	esp,8
	mov	eax,_122
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	call	_fdebuglog
	sub	esp,8
	mov	eax,4
	add	eax,[_varray_dummy_face]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_ttype_face
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbObjStore
	mov	[ebp-88],2
	jmp	_124
_123
	mov	[ebp-44],1
	sub	esp,8
	lea	eax,[ebp-48]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_125
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,8
	lea	eax,[ebp-96]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_126
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
_127
	sub	esp,20
	mov	ebx,[ebp-44]
	mov	[esp+4],ebx
	mov	[esp+8],1
	sub	esp,4
	mov	eax,[ebp-88]
	shl	eax,byte 2
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	_fmid
	mov	[esp+4],eax
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
	sub	esp,12
	lea	eax,[ebp-48]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_129
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_128
	sub	esp,20
	lea	eax,[ebp-96]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp+4],eax
	lea	ebx,[ebp-96]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
_128
	add	[ebp-44],1
	sub	esp,12
	lea	eax,[ebp-48]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_130
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jnz	_127
_24
	mov	ebx,[ebp-88]
	sub	ebx,1
	shl	ebx,byte 2
	mov	esi,4
	add	esi,[_varray_dummy_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,16
	mov	esi,[esi]
	add	ebx,esi
	sub	esp,8
	lea	eax,[ebp-96]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToInt
	mov	[ebx],eax
	add	[ebp-88],1
_124
	sub	esp,12
	mov	eax,[ebp-88]
	shl	eax,byte 2
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_131
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jnz	_123
_23
	mov	[ebp-100],0
	mov	[ebp-104],0
	mov	[ebp-108],0
	mov	[ebp-112],1
	jmp	_132
_133
	mov	ebx,[ebp-112]
	shl	ebx,byte 2
	mov	esi,4
	add	esi,[_varray_dummy_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,16
	mov	esi,[esi]
	add	ebx,esi
	mov	ebx,[ebx]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-100]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	esi
	fstp	[esp]
	pop	esi
	mov	[ebp-100],esi
	mov	ebx,[ebp-112]
	shl	ebx,byte 2
	mov	esi,4
	add	esi,[_varray_dummy_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,16
	mov	esi,[esi]
	add	ebx,esi
	mov	ebx,[ebx]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,12
	mov	ebx,[ebx]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-104]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	esi
	fstp	[esp]
	pop	esi
	mov	[ebp-104],esi
	mov	ebx,[ebp-112]
	shl	ebx,byte 2
	mov	esi,4
	add	esi,[_varray_dummy_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,16
	mov	esi,[esi]
	add	ebx,esi
	mov	ebx,[ebx]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-108]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	esi
	fstp	[esp]
	pop	esi
	mov	[ebp-108],esi
	add	[ebp-112],1
_132
	cmp	[ebp-112],4
	jle	_133
_25
	mov	ebx,[ebp-100]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1082130432
	push	esi
	fld	[esp]
	pop	esi
	fdivp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-100],ebx
	mov	ebx,[ebp-104]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1082130432
	push	esi
	fld	[esp]
	pop	esi
	fdivp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-104],ebx
	mov	ebx,[ebp-108]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1082130432
	push	esi
	fld	[esp]
	pop	esi
	fdivp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-108],ebx
	sub	esp,20
	mov	ebx,[ebp-108]
	mov	[esp+12],ebx
	mov	[esp+16],1
	mov	esi,[ebp-104]
	mov	[esp+8],esi
	mov	ebx,[ebp-100]
	mov	[esp+4],ebx
	mov	eax,[ebp-80]
	mov	[esp],eax
	call	_fpositionentity
	sub	esp,48
	mov	eax,_134
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-100]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrFromFloat
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_135
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-104]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrFromFloat
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_136
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-108]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrFromFloat
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
_121
	jmp	_70
_70
	sub	esp,4
	mov	eax,[ebp-60]
	mov	[esp],eax
	call	_feof
	and	eax,eax
	jz	_68
_16
	mov	[ebp-116],1
	jmp	_137
_138
	mov	[ebp-120],0
	sub	esp,8
	lea	eax,[ebp-124]
	mov	[esp],eax
	mov	[esp+4],_ttype_surface
	call	__bbObjEachFirst
	and	eax,eax
	jz	_27
_139
	sub	esp,12
	mov	eax,[ebp-124]
	mov	eax,[eax]
	add	eax,8
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jnz	_140
	mov	ebx,[ebp-124]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[ebp-120],ebx
_140
	sub	esp,4
	lea	eax,[ebp-124]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_139
_27
	cmp	[ebp-120],0
	jnz	_141
	sub	esp,8
	mov	eax,[ebp-40]
	shl	eax,byte 2
	add	eax,[_varray_surface]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_ttype_surface
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbObjStore
	mov	ebx,[ebp-40]
	mov	esi,[ebp-40]
	shl	esi,byte 2
	add	esi,[_varray_surface]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,0
	mov	[esi],ebx
	sub	esp,8
	mov	eax,[ebp-4]
	mov	[esp],eax
	mov	[esp+4],0
	call	_fcreatesurface
	mov	ebx,[ebp-40]
	shl	ebx,byte 2
	add	ebx,[_varray_surface]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	[ebx],eax
	sub	esp,8
	mov	eax,[ebp-40]
	shl	eax,byte 2
	add	eax,[_varray_surface]
	mov	eax,[eax]
	mov	eax,[eax]
	add	eax,8
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	mov	ebx,[ebp-40]
	shl	ebx,byte 2
	add	ebx,[_varray_surface]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[ebp-120],ebx
	add	[ebp-40],1
_141
	mov	[ebp-128],1
	jmp	_142
_143
	mov	ebx,[ebp-128]
	shl	ebx,byte 2
	mov	esi,[ebp-116]
	shl	esi,byte 2
	add	esi,[_varray_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,16
	mov	esi,[esi]
	add	ebx,esi
	mov	ebx,[ebx]
	mov	[ebp-132],ebx
	mov	ebx,[ebp-128]
	shl	ebx,byte 2
	mov	esi,[ebp-116]
	shl	esi,byte 2
	add	esi,[_varray_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,20
	mov	esi,[esi]
	add	ebx,esi
	mov	ebx,[ebx]
	mov	[ebp-136],ebx
	mov	ebx,[ebp-128]
	shl	ebx,byte 2
	mov	esi,[ebp-116]
	shl	esi,byte 2
	add	esi,[_varray_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,24
	mov	esi,[esi]
	add	ebx,esi
	mov	ebx,[ebx]
	mov	[ebp-140],ebx
	mov	ebx,[ebp-132]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	cmp	ebx,-1
	jnz	_144
	sub	esp,28
	mov	[esp+20],0
	mov	[esp+24],1065353216
	mov	[esp+16],0
	mov	ebx,[ebp-132]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	mov	[esp+12],ebx
	mov	esi,[ebp-132]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,12
	mov	esi,[esi]
	mov	[esp+8],esi
	mov	ebx,[ebp-132]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	mov	eax,[ebp-120]
	mov	[esp],eax
	call	_faddvertex
	mov	ebx,[ebp-132]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	[ebx],eax
	sub	esp,20
	mov	ebx,[ebp-136]
	shl	ebx,byte 2
	add	ebx,[_varray_normal]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	[esp+12],ebx
	mov	esi,[ebp-136]
	shl	esi,byte 2
	add	esi,[_varray_normal]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,12
	mov	esi,[esi]
	mov	[esp+16],esi
	mov	esi,[ebp-136]
	shl	esi,byte 2
	add	esi,[_varray_normal]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	mov	[esp+8],esi
	mov	ebx,[ebp-132]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	mov	eax,[ebp-120]
	mov	[esp],eax
	call	_fvertexnormal
	sub	esp,24
	mov	[esp+16],1065353216
	mov	[esp+20],0
	mov	esi,[ebp-140]
	shl	esi,byte 2
	add	esi,[_varray_uvw]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,8
	mov	esi,[esi]
	mov	[esp+12],esi
	mov	ebx,[ebp-140]
	shl	ebx,byte 2
	add	ebx,[_varray_uvw]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[esp+8],ebx
	mov	esi,[ebp-132]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	mov	[esp+4],esi
	mov	eax,[ebp-120]
	mov	[esp],eax
	call	_fvertextexcoords
	mov	ebx,[ebp-140]
	shl	ebx,byte 2
	add	ebx,[_varray_uvw]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	esi,[ebp-132]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,20
	mov	[esi],ebx
	mov	ebx,[ebp-140]
	shl	ebx,byte 2
	add	ebx,[_varray_uvw]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	esi,[ebp-132]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,24
	mov	[esi],ebx
	jmp	_145
_144
	mov	ebx,[ebp-140]
	shl	ebx,byte 2
	add	ebx,[_varray_uvw]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[ebp-144],ebx
	mov	ebx,[ebp-140]
	shl	ebx,byte 2
	add	ebx,[_varray_uvw]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	[ebp-148],ebx
	mov	ebx,[ebp-132]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,20
	mov	ebx,[ebx]
	mov	[ebp-152],ebx
	mov	ebx,[ebp-132]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,24
	mov	ebx,[ebx]
	mov	[ebp-156],ebx
	sub	esp,4
	mov	eax,[ebp-152]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,[ebp-144]
	push	ebx
	fld	[esp]
	pop	ebx
	fsubp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp],eax
	call	__bbFAbs
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-160],eax
	sub	esp,4
	mov	eax,[ebp-156]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,[ebp-148]
	push	ebx
	fld	[esp]
	pop	ebx
	fsubp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp],eax
	call	__bbFAbs
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-164],eax
	mov	eax,[ebp-160]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,1008981770
	push	ebx
	fld	[esp]
	pop	ebx
	fucompp
	fnstsw	ax
	sahf
	setb	al
	movzx	eax,al
	mov	[ebp-216],eax
	mov	ebx,[ebp-164]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1008981770
	push	esi
	fld	[esp]
	pop	esi
	mov	eax,ebx
	fucompp
	fnstsw	ax
	sahf
	setb	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-216]
	or	eax,ebx
	and	eax,eax
	jz	_146
	sub	esp,8
	mov	eax,[ebp-20]
	shl	eax,byte 2
	add	eax,[_varray_vertex]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_ttype_vertex
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbObjStore
	mov	ebx,[ebp-20]
	mov	esi,[ebp-20]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,0
	mov	[esi],ebx
	mov	ebx,[ebp-132]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	esi,[ebp-20]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,8
	mov	[esi],ebx
	mov	ebx,[ebp-132]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,12
	mov	ebx,[ebx]
	mov	esi,[ebp-20]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,12
	mov	[esi],ebx
	mov	ebx,[ebp-132]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	mov	esi,[ebp-20]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,16
	mov	[esi],ebx
	sub	esp,28
	mov	[esp+20],0
	mov	[esp+24],1065353216
	mov	[esp+16],0
	mov	ebx,[ebp-20]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	mov	[esp+12],ebx
	mov	esi,[ebp-20]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,12
	mov	esi,[esi]
	mov	[esp+8],esi
	mov	ebx,[ebp-20]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	mov	eax,[ebp-120]
	mov	[esp],eax
	call	_faddvertex
	mov	ebx,[ebp-20]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	[ebx],eax
	sub	esp,20
	mov	ebx,[ebp-136]
	shl	ebx,byte 2
	add	ebx,[_varray_normal]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	[esp+12],ebx
	mov	esi,[ebp-136]
	shl	esi,byte 2
	add	esi,[_varray_normal]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,12
	mov	esi,[esi]
	mov	[esp+16],esi
	mov	esi,[ebp-136]
	shl	esi,byte 2
	add	esi,[_varray_normal]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	mov	[esp+8],esi
	mov	ebx,[ebp-20]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	mov	eax,[ebp-120]
	mov	[esp],eax
	call	_fvertexnormal
	sub	esp,24
	mov	[esp+16],1065353216
	mov	[esp+20],0
	mov	esi,[ebp-140]
	shl	esi,byte 2
	add	esi,[_varray_uvw]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,8
	mov	esi,[esi]
	mov	[esp+12],esi
	mov	ebx,[ebp-140]
	shl	ebx,byte 2
	add	ebx,[_varray_uvw]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[esp+8],ebx
	mov	esi,[ebp-20]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	mov	[esp+4],esi
	mov	eax,[ebp-120]
	mov	[esp],eax
	call	_fvertextexcoords
	mov	ebx,[ebp-140]
	shl	ebx,byte 2
	add	ebx,[_varray_uvw]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	esi,[ebp-20]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,20
	mov	[esi],ebx
	mov	ebx,[ebp-140]
	shl	ebx,byte 2
	add	ebx,[_varray_uvw]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	esi,[ebp-20]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,24
	mov	[esi],ebx
	mov	ebx,[ebp-128]
	shl	ebx,byte 2
	mov	esi,[ebp-116]
	shl	esi,byte 2
	add	esi,[_varray_face]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,16
	mov	esi,[esi]
	add	ebx,esi
	mov	esi,[ebp-20]
	mov	[ebx],esi
	add	[ebp-20],1
_146
_145
	add	[ebp-128],1
_142
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,12
	mov	ebx,[ebx]
	cmp	[ebp-128],ebx
	jle	_143
_28
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,12
	mov	ebx,[ebx]
	cmp	ebx,3
	jnz	_147
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	ebx,12
	mov	ebx,[ebx]
	mov	[ebp-168],ebx
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	[ebp-172],ebx
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[ebp-176],ebx
	sub	esp,16
	mov	ebx,[ebp-172]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[esp+8],ebx
	mov	esi,[ebp-176]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	mov	[esp+12],esi
	mov	esi,[ebp-168]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	mov	[esp+4],esi
	mov	eax,[ebp-120]
	mov	[esp],eax
	call	_faddtriangle
	mov	[ebp-180],eax
_147
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,12
	mov	ebx,[ebx]
	cmp	ebx,4
	jnz	_148
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	mov	[ebp-168],ebx
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	ebx,12
	mov	ebx,[ebx]
	mov	[ebp-172],ebx
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	[ebp-176],ebx
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_varray_face]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[ebp-184],ebx
	sub	esp,16
	mov	ebx,[ebp-172]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[esp+8],ebx
	mov	esi,[ebp-176]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	mov	[esp+12],esi
	mov	esi,[ebp-168]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	mov	[esp+4],esi
	mov	eax,[ebp-120]
	mov	[esp],eax
	call	_faddtriangle
	mov	[ebp-180],eax
	sub	esp,16
	mov	ebx,[ebp-176]
	shl	ebx,byte 2
	add	ebx,[_varray_vertex]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,4
	mov	ebx,[ebx]
	mov	[esp+8],ebx
	mov	esi,[ebp-184]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	mov	[esp+12],esi
	mov	esi,[ebp-168]
	shl	esi,byte 2
	add	esi,[_varray_vertex]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	esi,[esi]
	mov	[esp+4],esi
	mov	eax,[ebp-120]
	mov	[esp],eax
	call	_faddtriangle
	mov	[ebp-188],eax
_148
	add	[ebp-116],1
_137
	mov	ebx,[ebp-32]
	sub	ebx,1
	cmp	[ebp-116],ebx
	jle	_138
_26
	sub	esp,16
	mov	eax,_149
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	[ebp-220],eax
	sub	esp,4
	mov	ebx,[ebp-4]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fcountsurfaces
	mov	ebx,eax
	mov	eax,[ebp-220]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrFromInt
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
	mov	[ebp-112],1
	jmp	_150
_151
	sub	esp,48
	mov	eax,_152
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-112]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrFromInt
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_153
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	[ebp-220],eax
	sub	esp,4
	mov	[ebp-224],eax
	sub	esp,8
	mov	ebx,[ebp-4]
	mov	[esp],ebx
	mov	esi,[ebp-112]
	mov	[esp+4],esi
	mov	eax,ebx
	call	_fgetsurface
	mov	ebx,eax
	mov	eax,[ebp-224]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fcountvertices
	mov	ebx,eax
	mov	eax,[ebp-220]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrFromInt
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_154
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	[ebp-220],eax
	sub	esp,4
	mov	[ebp-224],eax
	sub	esp,8
	mov	ebx,[ebp-4]
	mov	[esp],ebx
	mov	esi,[ebp-112]
	mov	[esp+4],esi
	mov	eax,ebx
	call	_fgetsurface
	mov	ebx,eax
	mov	eax,[ebp-224]
	mov	[esp],ebx
	mov	eax,ebx
	call	_fcounttriangles
	mov	ebx,eax
	mov	eax,[ebp-220]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrFromInt
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
	add	[ebp-112],1
_150
	sub	esp,4
	mov	eax,[ebp-4]
	mov	[esp],eax
	call	_fcountsurfaces
	cmp	[ebp-112],eax
	jle	_151
_29
	sub	esp,16
	lea	eax,[ebp-56]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-8]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_freadfile
	mov	[ebp-60],eax
	mov	[ebp-192],1
	mov	ebx,[ebp-60]
	and	ebx,ebx
	jz	_155
	sub	esp,24
	mov	eax,_156
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-8]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_157
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
	sub	esp,8
	mov	eax,[ebp-60]
	mov	[esp],eax
	mov	[esp+4],0
	call	_fseekfile
_158
	sub	esp,8
	lea	eax,[ebp-68]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-60]
	mov	[esp],ebx
	mov	eax,ebx
	call	_freadline
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,12
	lea	eax,[ebp-68]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_159
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	_ffunc_parse_line
	sub	esp,8
	lea	eax,[ebp-196]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,4
	add	ebx,[_varray_line_elements]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,12
	lea	eax,[ebp-196]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_162
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_161
	sub	esp,12
	lea	eax,[ebp-196]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_164
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_163
	sub	esp,12
	lea	eax,[ebp-196]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_166
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_165
	sub	esp,12
	lea	eax,[ebp-196]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_168
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_167
	sub	esp,12
	lea	eax,[ebp-196]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_170
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_169
	sub	esp,12
	lea	eax,[ebp-196]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_172
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_171
	sub	esp,16
	mov	eax,_173
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-68]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
	jmp	_160
_161
	sub	esp,8
	mov	eax,[ebp-192]
	shl	eax,byte 2
	add	eax,[_varray_material]
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_ttype_material
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbObjStore
	mov	ebx,[ebp-192]
	mov	esi,[ebp-192]
	shl	esi,byte 2
	add	esi,[_varray_material]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,0
	mov	[esi],ebx
	sub	esp,8
	mov	eax,[ebp-192]
	shl	eax,byte 2
	add	eax,[_varray_material]
	mov	eax,[eax]
	mov	eax,[eax]
	add	eax,4
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,8
	add	ebx,[_varray_line_elements]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	jmp	_160
_163
	sub	esp,8
	mov	eax,8
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	push	eax
	fstp	[esp]
	pop	eax
	mov	ebx,[ebp-192]
	shl	ebx,byte 2
	add	ebx,[_varray_material]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,8
	mov	[ebx],eax
	jmp	_160
_165
	mov	ebx,1132396544
	push	ebx
	fld	[esp]
	pop	ebx
	sub	esp,8
	mov	eax,8
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	fmulp	st(1)
	push	ebx
	fistp	[esp]
	pop	ebx
	mov	esi,[ebp-192]
	shl	esi,byte 2
	add	esi,[_varray_material]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,12
	mov	[esi],ebx
	mov	ebx,1132396544
	push	ebx
	fld	[esp]
	pop	ebx
	sub	esp,8
	mov	eax,12
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	fmulp	st(1)
	push	ebx
	fistp	[esp]
	pop	ebx
	mov	esi,[ebp-192]
	shl	esi,byte 2
	add	esi,[_varray_material]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,16
	mov	[esi],ebx
	mov	ebx,1132396544
	push	ebx
	fld	[esp]
	pop	ebx
	sub	esp,8
	mov	eax,16
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToFloat
	fmulp	st(1)
	push	ebx
	fistp	[esp]
	pop	ebx
	mov	esi,[ebp-192]
	shl	esi,byte 2
	add	esi,[_varray_material]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,20
	mov	[esi],ebx
	jmp	_160
_167
	jmp	_160
_169
	mov	ebx,1006699012
	push	ebx
	fld	[esp]
	pop	ebx
	sub	esp,8
	mov	eax,8
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToInt
	push	eax
	fild	[esp]
	pop	eax
	fmulp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	esi,[ebp-192]
	shl	esi,byte 2
	add	esi,[_varray_material]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,24
	mov	[esi],ebx
	mov	eax,[ebp-192]
	shl	eax,byte 2
	add	eax,[_varray_material]
	mov	eax,[eax]
	mov	eax,[eax]
	add	eax,24
	mov	eax,[eax]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,1065353216
	push	ebx
	fld	[esp]
	pop	ebx
	fucompp
	fnstsw	ax
	sahf
	setb	al
	movzx	eax,al
	and	eax,eax
	jz	_174
	mov	ebx,1065353216
	mov	esi,[ebp-192]
	shl	esi,byte 2
	add	esi,[_varray_material]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,24
	mov	[esi],ebx
_174
	jmp	_160
_171
	sub	esp,8
	mov	eax,[ebp-192]
	shl	eax,byte 2
	add	eax,[_varray_material]
	mov	eax,[eax]
	mov	eax,[eax]
	add	eax,28
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,8
	add	ebx,[_varray_line_elements]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	jmp	_160
_160
	sub	esp,12
	mov	eax,[ebp-192]
	shl	eax,byte 2
	add	eax,[_varray_material]
	mov	eax,[eax]
	mov	eax,[eax]
	add	eax,4
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_175
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	_ffunc_parse_line
	sub	esp,24
	mov	eax,_176
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp+4],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_177
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+8],ebx
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,4
	add	ebx,[_varray_line_elements]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp],ebx
	mov	eax,ebx
	call	_freplace
	mov	ebx,eax
	mov	[esp+4],ebx
	lea	eax,[ebp-200]
	mov	[esp],eax
	call	__bbStrStore
	sub	esp,8
	mov	eax,8
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToInt
	mov	ebx,[ebp-192]
	shl	ebx,byte 2
	add	ebx,[_varray_material]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,32
	mov	[ebx],eax
	sub	esp,8
	mov	eax,12
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToInt
	mov	ebx,[ebp-192]
	shl	ebx,byte 2
	add	ebx,[_varray_material]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,36
	mov	[ebx],eax
	sub	esp,8
	mov	eax,16
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToInt
	mov	ebx,[ebp-192]
	shl	ebx,byte 2
	add	ebx,[_varray_material]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,40
	mov	[ebx],eax
	sub	esp,8
	mov	eax,20
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	__bbStrToInt
	mov	ebx,[ebp-192]
	shl	ebx,byte 2
	add	ebx,[_varray_material]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,44
	mov	[ebx],eax
	sub	esp,12
	lea	eax,[ebp-200]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-192]
	shl	ebx,byte 2
	add	ebx,[_varray_material]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,28
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_178
	sub	esp,8
	mov	eax,[ebp-192]
	shl	eax,byte 2
	add	eax,[_varray_material]
	mov	eax,[eax]
	mov	eax,[eax]
	add	eax,28
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-200]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,16
	mov	eax,_179
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-192]
	shl	ebx,byte 2
	add	ebx,[_varray_material]
	mov	ebx,[ebx]
	mov	ebx,[ebx]
	add	ebx,28
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
_178
	sub	esp,4
	mov	eax,[ebp-60]
	mov	[esp],eax
	call	_feof
	and	eax,eax
	jz	_158
_30
	jmp	_180
_155
	sub	esp,24
	mov	eax,_181
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	lea	ebx,[ebp-8]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_182
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
_180
	sub	esp,8
	lea	eax,[ebp-204]
	mov	[esp],eax
	mov	[esp+4],_ttype_material
	call	__bbObjEachFirst
	and	eax,eax
	jz	_32
_183
	sub	esp,12
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	push	ebx
	fild	[esp]
	pop	ebx
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+4],ebx
	mov	esi,[ebp-204]
	mov	esi,[esi]
	add	esi,20
	mov	esi,[esi]
	push	esi
	fild	[esp]
	pop	esi
	push	esi
	fstp	[esp]
	pop	esi
	mov	[esp+8],esi
	mov	eax,[ebp-204]
	mov	eax,[eax]
	add	eax,12
	mov	eax,[eax]
	push	eax
	fild	[esp]
	pop	eax
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp],eax
	call	_fcreatebrush
	mov	[ebp-208],eax
	sub	esp,8
	mov	eax,[ebp-208]
	mov	[esp],eax
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,32
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	call	_fbrushblend
	sub	esp,8
	mov	eax,[ebp-208]
	mov	[esp],eax
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,36
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	call	_fbrushfx
	sub	esp,8
	mov	eax,[ebp-208]
	mov	[esp],eax
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,8
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	call	_fbrushalpha
	sub	esp,8
	mov	eax,[ebp-208]
	mov	[esp],eax
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,24
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	call	_fbrushshininess
	sub	esp,16
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,16
	mov	ebx,[ebx]
	push	ebx
	fild	[esp]
	pop	ebx
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+8],ebx
	mov	esi,[ebp-204]
	mov	esi,[esi]
	add	esi,20
	mov	esi,[esi]
	push	esi
	fild	[esp]
	pop	esi
	push	esi
	fstp	[esp]
	pop	esi
	mov	[esp+12],esi
	mov	esi,[ebp-204]
	mov	esi,[esi]
	add	esi,12
	mov	esi,[esi]
	push	esi
	fild	[esp]
	pop	esi
	push	esi
	fstp	[esp]
	pop	esi
	mov	[esp+4],esi
	mov	eax,[ebp-208]
	mov	[esp],eax
	call	_fbrushcolor
	sub	esp,20
	lea	eax,[ebp-56]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,28
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,44
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	call	_floadtexture
	mov	[ebp-212],eax
	sub	esp,8
	mov	eax,[ebp-212]
	mov	[esp],eax
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,40
	mov	ebx,[ebx]
	mov	[esp+4],ebx
	call	_ftextureblend
	mov	ebx,[ebp-212]
	and	ebx,ebx
	jz	_184
	sub	esp,32
	mov	eax,_185
	mov	[esp],eax
	call	__bbStrConst
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,28
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,_186
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-204]
	mov	ebx,[ebx]
	add	ebx,44
	mov	ebx,[ebx]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrFromInt
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp],eax
	call	_fdebuglog
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],0
	mov	esi,[ebp-212]
	mov	[esp+4],esi
	mov	eax,[ebp-208]
	mov	[esp],eax
	call	_fbrushtexture
_184
	sub	esp,8
	lea	eax,[ebp-124]
	mov	[esp],eax
	mov	[esp+4],_ttype_surface
	call	__bbObjEachFirst
	and	eax,eax
	jz	_33
_187
	sub	esp,12
	mov	eax,[ebp-204]
	mov	eax,[eax]
	add	eax,28
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-124]
	mov	ebx,[ebx]
	add	ebx,8
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jnz	_188
	sub	esp,8
	mov	eax,[ebp-124]
	mov	eax,[eax]
	add	eax,4
	mov	eax,[eax]
	mov	[esp],eax
	mov	ebx,[ebp-208]
	mov	[esp+4],ebx
	call	_fpaintsurface
_188
	sub	esp,4
	lea	eax,[ebp-124]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_187
_33
	sub	esp,4
	lea	eax,[ebp-204]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_183
_32
	call	_ffunc_cleanup
	mov	eax,[ebp-4]
	jmp	_14_leave
	jmp	_189
_65
	mov	eax,-1
	jmp	_14_leave
_189
	mov	eax,0
	jmp	_14_leave
_14_leave
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-200]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrRelease
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	esi,[ebp-204]
	mov	[esp],esi
	mov	eax,esi
	call	__bbObjRelease
	mov	esi,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	esi,[ebp-196]
	mov	[esp],esi
	mov	eax,esi
	call	__bbStrRelease
	mov	esi,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-124]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjRelease
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	esi,[ebp-96]
	mov	[esp],esi
	mov	eax,esi
	call	__bbStrRelease
	mov	esi,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-84]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrRelease
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	esi,[ebp-76]
	mov	[esp],esi
	mov	eax,esi
	call	__bbStrRelease
	mov	esi,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-72]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrRelease
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	esi,[ebp-68]
	mov	[esp],esi
	mov	eax,esi
	call	__bbStrRelease
	mov	esi,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-56]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrRelease
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	esi,[ebp-52]
	mov	[esp],esi
	mov	eax,esi
	call	__bbStrRelease
	mov	esi,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-48]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrRelease
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	esi,[ebp-16]
	mov	[esp],esi
	mov	eax,esi
	call	__bbStrRelease
	mov	esi,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp-12]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrRelease
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	esi,[ebp-8]
	mov	[esp],esi
	mov	eax,esi
	call	__bbStrRelease
	mov	esi,eax
	mov	eax,[ebp-216]
	mov	[ebp-216],eax
	sub	esp,4
	mov	ebx,[ebp+20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrRelease
	mov	ebx,eax
	mov	eax,[ebp-216]
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 4
	.align	16
_ffunc_cleanup
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,28
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	mov	[ebp-20],ebx
	mov	[ebp-24],ebx
	sub	esp,8
	lea	eax,[ebp-4]
	mov	[esp],eax
	mov	[esp+4],_ttype_vertex
	call	__bbObjEachFirst
	and	eax,eax
	jz	_35
_190
	sub	esp,4
	mov	eax,[ebp-4]
	mov	[esp],eax
	call	__bbObjDelete
	sub	esp,4
	lea	eax,[ebp-4]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_190
_35
	sub	esp,8
	lea	eax,[ebp-8]
	mov	[esp],eax
	mov	[esp+4],_ttype_normal
	call	__bbObjEachFirst
	and	eax,eax
	jz	_36
_191
	sub	esp,4
	mov	eax,[ebp-8]
	mov	[esp],eax
	call	__bbObjDelete
	sub	esp,4
	lea	eax,[ebp-8]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_191
_36
	sub	esp,8
	lea	eax,[ebp-12]
	mov	[esp],eax
	mov	[esp+4],_ttype_uvw
	call	__bbObjEachFirst
	and	eax,eax
	jz	_37
_192
	sub	esp,4
	mov	eax,[ebp-12]
	mov	[esp],eax
	call	__bbObjDelete
	sub	esp,4
	lea	eax,[ebp-12]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_192
_37
	sub	esp,8
	lea	eax,[ebp-16]
	mov	[esp],eax
	mov	[esp+4],_ttype_face
	call	__bbObjEachFirst
	and	eax,eax
	jz	_38
_193
	sub	esp,4
	mov	eax,[ebp-16]
	mov	[esp],eax
	call	__bbObjDelete
	sub	esp,4
	lea	eax,[ebp-16]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_193
_38
	sub	esp,8
	lea	eax,[ebp-20]
	mov	[esp],eax
	mov	[esp+4],_ttype_surface
	call	__bbObjEachFirst
	and	eax,eax
	jz	_39
_194
	sub	esp,4
	mov	eax,[ebp-20]
	mov	[esp],eax
	call	__bbObjDelete
	sub	esp,4
	lea	eax,[ebp-20]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_194
_39
	sub	esp,8
	lea	eax,[ebp-24]
	mov	[esp],eax
	mov	[esp+4],_ttype_material
	call	__bbObjEachFirst
	and	eax,eax
	jz	_40
_195
	sub	esp,4
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	__bbObjDelete
	sub	esp,4
	lea	eax,[ebp-24]
	mov	[esp],eax
	call	__bbObjEachNext
	and	eax,eax
	jnz	_195
_40
	mov	eax,0
	jmp	_34_leave
_34_leave
	mov	[ebp-28],eax
	sub	esp,4
	mov	ebx,[ebp-20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjRelease
	mov	ebx,eax
	mov	eax,[ebp-28]
	mov	[ebp-28],eax
	sub	esp,4
	mov	esi,[ebp-24]
	mov	[esp],esi
	mov	eax,esi
	call	__bbObjRelease
	mov	esi,eax
	mov	eax,[ebp-28]
	mov	[ebp-28],eax
	sub	esp,4
	mov	esi,[ebp-16]
	mov	[esp],esi
	mov	eax,esi
	call	__bbObjRelease
	mov	esi,eax
	mov	eax,[ebp-28]
	mov	[ebp-28],eax
	sub	esp,4
	mov	ebx,[ebp-12]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjRelease
	mov	ebx,eax
	mov	eax,[ebp-28]
	mov	[ebp-28],eax
	sub	esp,4
	mov	esi,[ebp-8]
	mov	[esp],esi
	mov	eax,esi
	call	__bbObjRelease
	mov	esi,eax
	mov	eax,[ebp-28]
	mov	[ebp-28],eax
	sub	esp,4
	mov	ebx,[ebp-4]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjRelease
	mov	ebx,eax
	mov	eax,[ebp-28]
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 0
	.align	16
_ffunc_parse_line
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,32
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	mov	[ebp-20],ebx
	mov	[ebp-4],1
	jmp	_196
_197
	sub	esp,8
	mov	eax,[ebp-4]
	shl	eax,byte 2
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	mov	[ebp-24],eax
	sub	esp,4
	mov	ebx,_198
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-24]
	mov	[esp+4],ebx
	call	__bbStrStore
	add	[ebp-4],1
_196
	cmp	[ebp-4],100
	jle	_197
_42
	mov	[ebp-8],1
	mov	[ebp-12],1
_199
	sub	esp,8
	lea	eax,[ebp-16]
	mov	[esp],eax
	mov	[ebp-24],eax
	sub	esp,4
	mov	ebx,_200
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-24]
	mov	[esp+4],ebx
	call	__bbStrStore
	sub	esp,8
	lea	eax,[ebp-20]
	mov	[esp],eax
	mov	[ebp-24],eax
	sub	esp,4
	mov	ebx,_201
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-24]
	mov	[esp+4],ebx
	call	__bbStrStore
_202
	sub	esp,20
	mov	ebx,[ebp-8]
	mov	[esp+4],ebx
	mov	[esp+8],1
	sub	esp,4
	lea	eax,[ebp+20]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	_fmid
	mov	[esp+4],eax
	lea	ebx,[ebp-16]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
	add	[ebp-8],1
	sub	esp,12
	lea	eax,[ebp-16]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-24],eax
	sub	esp,4
	mov	ebx,_204
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrConst
	mov	ebx,eax
	mov	eax,[ebp-24]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	jz	_203
	sub	esp,20
	lea	eax,[ebp-20]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-24],eax
	sub	esp,4
	lea	ebx,[ebp-16]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-24]
	mov	[esp+4],ebx
	call	__bbStrConcat
	mov	[esp+4],eax
	lea	ebx,[ebp-20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrStore
	mov	ebx,eax
_203
	sub	esp,12
	lea	eax,[ebp-16]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	mov	[ebp-24],eax
	sub	esp,4
	lea	ebx,[ebp+24]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-24]
	mov	[esp+4],ebx
	call	__bbStrCompare
	cmp	eax,0
	setz	al
	movzx	eax,al
	mov	[ebp-24],eax
	mov	[ebp-28],eax
	sub	esp,4
	mov	[ebp-32],eax
	sub	esp,4
	lea	ebx,[ebp+20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-32]
	mov	[esp],ebx
	mov	eax,ebx
	call	_flen
	mov	ebx,eax
	mov	eax,[ebp-28]
	cmp	[ebp-8],ebx
	mov	eax,ebx
	setg	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-24]
	or	eax,ebx
	and	eax,eax
	jz	_202
_44
	sub	esp,8
	mov	eax,[ebp-12]
	shl	eax,byte 2
	add	eax,[_varray_line_elements]
	mov	[esp],eax
	mov	[ebp-24],eax
	sub	esp,4
	lea	ebx,[ebp-20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrLoad
	mov	ebx,eax
	mov	eax,[ebp-24]
	mov	[esp+4],ebx
	call	__bbStrStore
	add	[ebp-12],1
	sub	esp,8
	lea	eax,[ebp+20]
	mov	[esp],eax
	call	__bbStrLoad
	mov	[esp],eax
	call	_flen
	cmp	[ebp-8],eax
	jle	_199
_43
	mov	eax,0
	jmp	_41_leave
_41_leave
	mov	[ebp-24],eax
	sub	esp,4
	mov	ebx,[ebp-16]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrRelease
	mov	ebx,eax
	mov	eax,[ebp-24]
	mov	[ebp-24],eax
	sub	esp,4
	mov	esi,[ebp-20]
	mov	[esp],esi
	mov	eax,esi
	call	__bbStrRelease
	mov	esi,eax
	mov	eax,[ebp-24]
	mov	[ebp-24],eax
	sub	esp,4
	mov	esi,[ebp+24]
	mov	[esp],esi
	mov	eax,esi
	call	__bbStrRelease
	mov	esi,eax
	mov	eax,[ebp-24]
	mov	[ebp-24],eax
	sub	esp,4
	mov	ebx,[ebp+20]
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbStrRelease
	mov	ebx,eax
	mov	eax,[ebp-24]
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 8
	.align	4
_6	.dd	6
	.dd	101
	.dd	__bbStrType
_varray_line_elements	.dd	0
	.align	4
_7	.dd	6
	.dd	10001
	.dd	_ttype_vertex
_varray_vertex	.dd	0
	.align	4
_8	.dd	6
	.dd	10001
	.dd	_ttype_normal
_varray_normal	.dd	0
	.align	4
_9	.dd	6
	.dd	20001
	.dd	_ttype_uvw
_varray_uvw	.dd	0
	.align	4
_10	.dd	6
	.dd	5001
	.dd	_ttype_face
_varray_face	.dd	0
	.align	4
_11	.dd	6
	.dd	101
	.dd	_ttype_surface
_varray_surface	.dd	0
	.align	4
_12	.dd	6
	.dd	11
	.dd	_ttype_material
_varray_material	.dd	0
	.align	4
_13	.dd	6
	.dd	7
	.dd	_ttype_face
_varray_dummy_face	.dd	0
	.align	4
_ttype_vertex	.dd	5
_45	.dd	0
	.dd	_45
	.dd	_45
	.dd	0
	.dd	-1
_46	.dd	0
	.dd	_46
	.dd	_46
	.dd	0
	.dd	-1
	.dd	7
	.dd	__bbIntType
	.dd	__bbIntType
	.dd	__bbFltType
	.dd	__bbFltType
	.dd	__bbFltType
	.dd	__bbFltType
	.dd	__bbFltType
	.align	4
_ttype_normal	.dd	5
_47	.dd	0
	.dd	_47
	.dd	_47
	.dd	0
	.dd	-1
_48	.dd	0
	.dd	_48
	.dd	_48
	.dd	0
	.dd	-1
	.dd	4
	.dd	__bbIntType
	.dd	__bbFltType
	.dd	__bbFltType
	.dd	__bbFltType
	.align	4
_ttype_uvw	.dd	5
_49	.dd	0
	.dd	_49
	.dd	_49
	.dd	0
	.dd	-1
_50	.dd	0
	.dd	_50
	.dd	_50
	.dd	0
	.dd	-1
	.dd	3
	.dd	__bbIntType
	.dd	__bbFltType
	.dd	__bbFltType
	.align	4
_ttype_surface	.dd	5
_51	.dd	0
	.dd	_51
	.dd	_51
	.dd	0
	.dd	-1
_52	.dd	0
	.dd	_52
	.dd	_52
	.dd	0
	.dd	-1
	.dd	3
	.dd	__bbIntType
	.dd	__bbIntType
	.dd	__bbStrType
	.align	4
_3	.dd	6
	.dd	11
	.dd	__bbIntType
	.align	4
_4	.dd	6
	.dd	11
	.dd	__bbIntType
	.align	4
_5	.dd	6
	.dd	11
	.dd	__bbIntType
	.align	4
_ttype_face	.dd	5
_53	.dd	0
	.dd	_53
	.dd	_53
	.dd	0
	.dd	-1
_54	.dd	0
	.dd	_54
	.dd	_54
	.dd	0
	.dd	-1
	.dd	7
	.dd	__bbIntType
	.dd	__bbIntType
	.dd	__bbStrType
	.dd	__bbIntType
	.dd	_3
	.dd	_4
	.dd	_5
	.align	4
_ttype_material	.dd	5
_55	.dd	0
	.dd	_55
	.dd	_55
	.dd	0
	.dd	-1
_56	.dd	0
	.dd	_56
	.dd	_56
	.dd	0
	.dd	-1
	.dd	12
	.dd	__bbIntType
	.dd	__bbStrType
	.dd	__bbFltType
	.dd	__bbIntType
	.dd	__bbIntType
	.dd	__bbIntType
	.dd	__bbFltType
	.dd	__bbStrType
	.dd	__bbIntType
	.dd	__bbIntType
	.dd	__bbIntType
	.dd	__bbIntType
_57	.db	"",0
_58	.db	"",0
_59	.db	"",0
_61	.db	"\",0
_64	.db	"",0
_66	.db	"---- OBJ LOADER - ",0
_67	.db	" ------------------------------------------------------------",0
_69	.db	" ",0
_72	.db	"",0
_74	.db	"mtllib",0
_76	.db	"o",0
_78	.db	"v",0
_80	.db	"vn",0
_82	.db	"vt",0
_84	.db	"g",0
_86	.db	"usemtl",0
_88	.db	"f",0
_89	.db	"ERROR : MESH FILE : LINE NOT RECOGNIZED : ",0
_91	.db	"DUMMY",0
_92	.db	"Child object ",0
_93	.db	" created.",0
_97	.db	"_",0
_101	.db	"",0
_102	.db	"",0
_105	.db	"/",0
_106	.db	"/",0
_107	.db	"",0
_108	.db	"",0
_111	.db	"/",0
_112	.db	"/",0
_113	.db	"",0
_114	.db	"",0
_117	.db	"/",0
_118	.db	"/",0
_119	.db	"",0
_120	.db	"",0
_122	.db	"DUMMY OBJECT FACE FOUND",0
_125	.db	"",0
_126	.db	"",0
_129	.db	"/",0
_130	.db	"/",0
_131	.db	"",0
_134	.db	"dummy object position : ",0
_135	.db	" , ",0
_136	.db	" , ",0
_149	.db	"   Mesh : surface count : ",0
_152	.db	"      Mesh : Surface ",0
_153	.db	" - vertex count : ",0
_154	.db	"    triangle count : ",0
_156	.db	"   Material file ",0
_157	.db	" found.",0
_159	.db	" ",0
_162	.db	"newmtl",0
_164	.db	"Ka",0
_166	.db	"Kd",0
_168	.db	"Ks",0
_170	.db	"Ns",0
_172	.db	"map_Kd",0
_173	.db	"ERROR : MATERIAL FILE : LINE NOT RECOGNIZED : ",0
_175	.db	"_",0
_176	.db	"_",0
_177	.db	"",0
_179	.db	"TEXTURE NAME OVERRIDE : Setting texture to ",0
_181	.db	"ERROR : MATERIAL FILE : ",0
_182	.db	" NOT FOUND.",0
_185	.db	"   Texture ",0
_186	.db	" loaded : flags ",0
_198	.db	"",0
_200	.db	"",0
_201	.db	"",0
_204	.db	" ",0
	.align	4
__LIBS
	.db	"",0
	.align	4
__DATA
	.dd	0

