
	.align	16
__MAIN
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,72
	sub	esp,4
	mov	eax,__DATA
	mov	[esp],eax
	call	__bbRestore
	sub	esp,4
	mov	eax,__LIBS
	mov	[esp],eax
	call	__bbLoadLibs
	call	_2_begin
	jmp	_2_leave
_2_begin
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	mov	[ebp-20],ebx
	mov	[ebp-24],ebx
	mov	[ebp-28],ebx
	mov	[ebp-32],ebx
	mov	[ebp-36],ebx
	mov	[ebp-40],ebx
	mov	[ebp-44],ebx
	mov	[ebp-48],ebx
	mov	[ebp-52],ebx
	mov	[ebp-56],ebx
	mov	[ebp-60],ebx
	mov	[ebp-64],ebx
	mov	[ebp-68],ebx
	sub	esp,4
	mov	eax,_3
	mov	[esp],eax
	call	__bbVecAlloc
	mov	[_vctrlpoints],eax
	sub	esp,4
	mov	eax,_atring
	mov	[esp],eax
	call	__bbUndimArray
	mov	ebx,0
	mov	esi,_atring
	add	esi,12
	mov	[esi],ebx
	sub	esp,4
	mov	eax,_atring
	mov	[esp],eax
	call	__bbDimArray
	sub	esp,4
	mov	eax,_abring
	mov	[esp],eax
	call	__bbUndimArray
	mov	ebx,0
	mov	esi,_abring
	add	esi,12
	mov	[esi],ebx
	sub	esp,4
	mov	eax,_abring
	mov	[esp],eax
	call	__bbDimArray
	mov	[_vctrlpointsphase],0
	mov	[_vctrlpointsphase2],0
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],2
	mov	[esp+4],480
	mov	[esp],640
	call	_fgraphics3d
	sub	esp,4
	call	_fbackbuffer
	mov	[esp],eax
	call	_fsetbuffer
	sub	esp,12
	mov	[esp+4],0
	mov	[esp+8],0
	mov	[esp],1107296256
	call	_fambientlight
	sub	esp,4
	mov	[esp],0
	call	_fcreatecamera
	mov	[ebp-4],eax
	sub	esp,12
	mov	[esp+4],1036831949
	mov	[esp+8],1157234688
	mov	eax,[ebp-4]
	mov	[esp],eax
	call	_fcamerarange
	sub	esp,8
	mov	[esp],1
	mov	[esp+4],0
	call	_fcreatelight
	mov	[ebp-8],eax
	sub	esp,20
	mov	[esp+12],0
	mov	[esp+16],0
	mov	[esp+8],0
	mov	[esp+4],1119092736
	mov	eax,[ebp-8]
	mov	[esp],eax
	call	_frotateentity
	mov	[_vvsegs],32
	mov	[_vrsegs],16
	sub	esp,16
	mov	[esp+8],9
	mov	[esp+12],1
	mov	[esp+4],32
	mov	[esp],32
	call	_fcreatetexture
	mov	[ebp-12],eax
	sub	esp,12
	mov	eax,[ebp-12]
	mov	[esp],eax
	mov	[esp+4],0
	call	_ftexturebuffer
	mov	[esp],eax
	call	_fsetbuffer
	mov	[ebp-16],128
	mov	[ebp-20],0
	jmp	_19
_20
	mov	ebx,64
	sub	ebx,[ebp-16]
	mov	[ebp-16],ebx
	mov	[ebp-24],0
	jmp	_21
_22
	mov	ebx,64
	sub	ebx,[ebp-16]
	mov	[ebp-16],ebx
	sub	esp,12
	mov	ebx,[ebp-16]
	mov	[esp+4],ebx
	mov	esi,[ebp-16]
	mov	[esp+8],esi
	mov	eax,[ebp-16]
	mov	[esp],eax
	call	_fcolor
	sub	esp,20
	mov	[esp+12],8
	mov	[esp+16],1
	mov	[esp+8],8
	mov	ebx,[ebp-20]
	mov	[esp+4],ebx
	mov	eax,[ebp-24]
	mov	[esp],eax
	call	_frect
	add	[ebp-24],8
_21
	cmp	[ebp-24],31
	jle	_22
_5
	add	[ebp-20],8
_19
	cmp	[ebp-20],31
	jle	_20
_4
	sub	esp,4
	call	_fbackbuffer
	mov	[esp],eax
	call	_fsetbuffer
	sub	esp,12
	mov	[esp+4],1048576000
	mov	[esp+8],1048576000
	mov	eax,[ebp-12]
	mov	[esp],eax
	call	_fscaletexture
	sub	esp,16
	mov	[esp+8],13
	mov	[esp+12],1
	mov	[esp+4],64
	mov	[esp],64
	call	_fcreatetexture
	mov	[ebp-28],eax
	sub	esp,12
	mov	eax,[ebp-28]
	mov	[esp],eax
	mov	[esp+4],0
	call	_ftexturebuffer
	mov	[esp],eax
	call	_fsetbuffer
	mov	[ebp-20],0
	jmp	_23
_24
	sub	esp,8
	mov	[esp],10
	mov	[esp+4],64
	call	_frand
	mov	[ebp-16],eax
	sub	esp,8
	mov	[esp],0
	mov	[esp+4],128
	call	_frand
	mov	[ebp-32],eax
	sub	esp,8
	mov	[esp],0
	mov	[esp+4],180
	call	_frand
	mov	[ebp-36],eax
	sub	esp,12
	mov	ebx,[ebp-32]
	mov	[esp+4],ebx
	mov	esi,[ebp-36]
	mov	[esp+8],esi
	mov	eax,[ebp-16]
	mov	[esp],eax
	call	_fcolor
	sub	esp,28
	mov	[esp],1
	mov	[esp+4],2
	call	_frand
	mov	[esp+8],eax
	mov	[ebp-72],eax
	sub	esp,8
	mov	[esp],1
	mov	[esp+4],31
	mov	eax,ebx
	call	_frand
	mov	ebx,eax
	mov	eax,[ebp-72]
	mov	[esp+12],ebx
	mov	[esp+16],1
	mov	[ebp-72],eax
	sub	esp,8
	mov	[esp],0
	mov	[esp+4],63
	mov	eax,ebx
	call	_frand
	mov	ebx,eax
	mov	eax,[ebp-72]
	mov	[esp+4],ebx
	sub	esp,8
	mov	[esp],0
	mov	[esp+4],63
	call	_frand
	mov	[esp],eax
	call	_frect
	sub	esp,28
	mov	[esp],1
	mov	[esp+4],31
	call	_frand
	mov	[esp+8],eax
	mov	[ebp-72],eax
	sub	esp,8
	mov	[esp],1
	mov	[esp+4],2
	mov	eax,ebx
	call	_frand
	mov	ebx,eax
	mov	eax,[ebp-72]
	mov	[esp+12],ebx
	mov	[esp+16],1
	mov	[ebp-72],eax
	sub	esp,8
	mov	[esp],0
	mov	[esp+4],63
	mov	eax,ebx
	call	_frand
	mov	ebx,eax
	mov	eax,[ebp-72]
	mov	[esp+4],ebx
	sub	esp,8
	mov	[esp],0
	mov	[esp+4],63
	call	_frand
	mov	[esp],eax
	call	_frect
	add	[ebp-20],1
_23
	cmp	[ebp-20],16
	jle	_24
_6
	sub	esp,4
	call	_fbackbuffer
	mov	[esp],eax
	call	_fsetbuffer
	sub	esp,12
	mov	[esp+4],1036831949
	mov	[esp+8],1048576000
	mov	eax,[ebp-28]
	mov	[esp],eax
	call	_fscaletexture
	sub	esp,8
	mov	eax,[ebp-12]
	mov	[esp],eax
	mov	[esp+4],2
	call	_ftextureblend
	sub	esp,8
	mov	eax,[ebp-28]
	mov	[esp],eax
	mov	[esp+4],3
	call	_ftextureblend
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],0
	mov	esi,[_vrsegs]
	mov	[esp+4],esi
	mov	eax,[_vvsegs]
	mov	[esp],eax
	call	_fcreatemycylinder
	mov	[ebp-40],eax
	sub	esp,16
	mov	[esp+8],1109393408
	mov	[esp+12],1086324736
	mov	[esp+4],1086324736
	mov	eax,[ebp-40]
	mov	[esp],eax
	call	_fscalemesh
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],0
	mov	[esp+4],1119092736
	mov	eax,[ebp-40]
	mov	[esp],eax
	call	_frotatemesh
	sub	esp,4
	mov	eax,[ebp-40]
	mov	[esp],eax
	call	_fflipmesh
	sub	esp,20
	mov	[esp+12],1109131264
	mov	[esp+16],0
	mov	[esp+8],0
	mov	[esp+4],0
	mov	eax,[ebp-40]
	mov	[esp],eax
	call	_fpositionentity
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],0
	mov	esi,[ebp-12]
	mov	[esp+4],esi
	mov	eax,[ebp-40]
	mov	[esp],eax
	call	_fentitytexture
	sub	esp,16
	mov	[esp+8],0
	mov	[esp+12],1
	mov	esi,[ebp-28]
	mov	[esp+4],esi
	mov	eax,[ebp-40]
	mov	[esp],eax
	call	_fentitytexture
	sub	esp,8
	mov	eax,[ebp-40]
	mov	[esp],eax
	mov	[esp+4],0
	call	_fcopymesh
	mov	[ebp-44],eax
	sub	esp,4
	mov	eax,[ebp-44]
	mov	[esp],eax
	call	_fhideentity
	mov	[ebp-24],0
	jmp	_25
_26
	sub	esp,8
	mov	eax,[ebp-24]
	shl	eax,byte 2
	add	eax,[_vctrlpoints]
	mov	[esp],eax
	mov	[ebp-72],eax
	sub	esp,4
	mov	ebx,_ttctrlpoint
	mov	[esp],ebx
	mov	eax,ebx
	call	__bbObjNew
	mov	ebx,eax
	mov	eax,[ebp-72]
	mov	[esp+4],ebx
	call	__bbObjStore
	mov	ebx,[ebp-24]
	imul	ebx,260
	sar	ebx,byte 4
	push	ebx
	fild	[esp]
	pop	ebx
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	esi,[ebp-24]
	shl	esi,byte 2
	add	esi,[_vctrlpoints]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,0
	mov	[esi],ebx
	mov	ebx,[ebp-24]
	imul	ebx,460
	sar	ebx,byte 4
	push	ebx
	fild	[esp]
	pop	ebx
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	esi,[ebp-24]
	shl	esi,byte 2
	add	esi,[_vctrlpoints]
	mov	esi,[esi]
	mov	esi,[esi]
	add	esi,4
	mov	[esi],ebx
	add	[ebp-24],1
_25
	cmp	[ebp-24],16
	jle	_26
_7
	mov	[ebp-48],0
	mov	[ebp-52],0
	mov	[ebp-56],0
	mov	[ebp-60],1
	mov	[ebp-64],1
	jmp	_28
_27
	sub	esp,16
	mov	ebx,[_vctrlpointsphase]
	mov	[esp+8],ebx
	mov	esi,[_vctrlpointsphase2]
	mov	[esp+12],esi
	mov	esi,[ebp-44]
	mov	[esp+4],esi
	mov	eax,[ebp-40]
	mov	[esp],eax
	call	_ftunnel_effect
	mov	ebx,[ebp-60]
	add	[_vctrlpointsphase],ebx
	mov	ebx,[ebp-64]
	add	[_vctrlpointsphase2],ebx
	sub	esp,8
	mov	[esp],0
	mov	[esp+4],200
	call	_frand
	cmp	eax,0
	jnz	_29
	sub	esp,8
	mov	[esp],0
	mov	[esp+4],4
	call	_frand
	mov	[ebp-64],eax
_29
	sub	esp,8
	mov	[esp],0
	mov	[esp+4],400
	call	_frand
	cmp	eax,0
	jnz	_30
	sub	esp,8
	mov	[esp],1
	mov	[esp+4],4
	call	_frand
	mov	[ebp-60],eax
_30
	sub	esp,12
	mov	[esp+4],0
	mov	esi,[ebp-56]
	mov	[esp+8],esi
	mov	eax,[ebp-12]
	mov	[esp],eax
	call	_fpositiontexture
	sub	esp,12
	mov	ebx,[ebp-56]
	mov	[esp+4],ebx
	mov	esi,[ebp-56]
	mov	[esp+8],esi
	mov	eax,[ebp-28]
	mov	[esp],eax
	call	_fpositiontexture
	mov	ebx,1008981770
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-60]
	add	esi,[ebp-64]
	push	esi
	fild	[esp]
	pop	esi
	fmulp	st(1)
	mov	esi,1056964608
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	mov	esi,[ebp-56]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	esi
	fstp	[esp]
	pop	esi
	mov	[ebp-56],esi
	sub	esp,4
	mov	[esp],17
	call	_fkeydown
	mov	[ebp-72],eax
	cmp	[ebp-48],0
	mov	eax,ebx
	setz	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-72]
	and	eax,ebx
	and	eax,eax
	jz	_31
	mov	[ebp-48],1
_31
	sub	esp,4
	mov	[esp],17
	call	_fkeydown
	cmp	eax,0
	setz	al
	movzx	eax,al
	mov	[ebp-72],eax
	cmp	[ebp-48],1
	mov	eax,ebx
	setz	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-72]
	and	eax,ebx
	and	eax,eax
	jz	_32
	mov	[ebp-48],0
	cmp	[ebp-68],0
	jnz	_33
	mov	[ebp-68],1
	jmp	_34
_33
	mov	[ebp-68],0
_34
	cmp	[ebp-68],0
	jnz	_35
	sub	esp,4
	mov	[esp],0
	call	_fwireframe
_35
	cmp	[ebp-68],1
	jnz	_36
	sub	esp,4
	mov	[esp],1
	call	_fwireframe
_36
_32
	sub	esp,4
	mov	[esp],1065353216
	call	_frenderworld
	sub	esp,4
	mov	[esp],1
	call	_fflip
_28
	sub	esp,4
	mov	[esp],1
	call	_fkeydown
	cmp	eax,0
	jz	_27
_8
	call	_fend
	ret
_2_leave
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 0
	.align	16
_fcreatemycylinder
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,120
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	mov	[ebp-20],ebx
	mov	[ebp-24],ebx
	mov	[ebp-28],ebx
	mov	[ebp-32],ebx
	mov	[ebp-36],ebx
	mov	[ebp-40],ebx
	mov	[ebp-44],ebx
	mov	[ebp-48],ebx
	mov	[ebp-52],ebx
	mov	[ebp-56],ebx
	mov	[ebp-60],ebx
	mov	[ebp-64],ebx
	mov	[ebp-68],ebx
	mov	[ebp-72],ebx
	mov	[ebp-76],ebx
	mov	[ebp-80],ebx
	mov	[ebp-84],ebx
	mov	[ebp-88],ebx
	mov	[ebp-92],ebx
	mov	[ebp-96],ebx
	mov	[ebp-100],ebx
	mov	[ebp-104],ebx
	mov	[ebp-108],ebx
	mov	[ebp-112],ebx
	mov	[ebp-116],ebx
	cmp	[ebp+20],3
	setl	al
	movzx	eax,al
	mov	[ebp-120],eax
	cmp	[ebp+20],100
	mov	eax,ebx
	setg	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-120]
	or	eax,ebx
	and	eax,eax
	jz	_39
	mov	eax,0
	jmp	_9_leave
_39
	cmp	[ebp+24],0
	setl	al
	movzx	eax,al
	mov	[ebp-120],eax
	cmp	[ebp+24],100
	mov	eax,ebx
	setg	al
	movzx	eax,al
	mov	ebx,eax
	mov	eax,[ebp-120]
	or	eax,ebx
	and	eax,eax
	jz	_40
	mov	eax,0
	jmp	_9_leave
_40
	sub	esp,4
	mov	eax,[ebp+32]
	mov	[esp],eax
	call	_fcreatemesh
	mov	[ebp-44],eax
	sub	esp,8
	mov	eax,[ebp-44]
	mov	[esp],eax
	mov	[esp+4],0
	call	_fcreatesurface
	mov	[ebp-48],eax
	cmp	[ebp+28],1
	jnz	_41
	sub	esp,8
	mov	eax,[ebp-44]
	mov	[esp],eax
	mov	[esp+4],0
	call	_fcreatesurface
	mov	[ebp-52],eax
_41
	mov	ebx,1135869952
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp+20]
	push	esi
	fild	[esp]
	pop	esi
	fdivp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-56],ebx
	mov	[ebp-60],1065353216
	mov	ebx,[ebp-60]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1073741824
	push	esi
	fld	[esp]
	pop	esi
	fmulp	st(1)
	mov	esi,[ebp+24]
	add	esi,1
	push	esi
	fild	[esp]
	pop	esi
	fdivp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-64],ebx
	mov	[ebp-68],1065353216
	mov	ebx,1065353216
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp+20]
	push	esi
	fild	[esp]
	pop	esi
	fdivp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-72],ebx
	mov	[ebp-76],1065353216
	mov	ebx,1065353216
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp+24]
	add	esi,1
	push	esi
	fild	[esp]
	pop	esi
	fdivp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-80],ebx
	mov	[ebp-84],1119092736
	sub	esp,4
	mov	eax,_atring
	mov	[esp],eax
	call	__bbUndimArray
	mov	ebx,[ebp+20]
	mov	esi,_atring
	add	esi,12
	mov	[esi],ebx
	sub	esp,4
	mov	eax,_atring
	mov	[esp],eax
	call	__bbDimArray
	sub	esp,4
	mov	eax,_abring
	mov	[esp],eax
	call	__bbUndimArray
	mov	ebx,[ebp+20]
	mov	esi,_abring
	add	esi,12
	mov	[esi],ebx
	sub	esp,4
	mov	eax,_abring
	mov	[esp],eax
	call	__bbDimArray
	cmp	[ebp+28],1
	jnz	_42
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fcos
	fchs
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-88],eax
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fsin
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-92],eax
	sub	esp,28
	mov	ebx,[ebp-88]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1073741824
	push	esi
	fld	[esp]
	pop	esi
	fdivp	st(1)
	mov	esi,1056964608
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+16],ebx
	mov	esi,[ebp-92]
	push	esi
	fld	[esp]
	pop	esi
	mov	edi,1073741824
	push	edi
	fld	[esp]
	pop	edi
	fdivp	st(1)
	mov	edi,1056964608
	push	edi
	fld	[esp]
	pop	edi
	faddp	st(1)
	push	esi
	fstp	[esp]
	pop	esi
	mov	[esp+20],esi
	mov	[esp+24],1065353216
	mov	esi,[ebp-92]
	mov	[esp+12],esi
	mov	ebx,[ebp-60]
	mov	[esp+8],ebx
	mov	esi,[ebp-88]
	mov	[esp+4],esi
	mov	eax,[ebp-52]
	mov	[esp],eax
	call	_faddvertex
	mov	[ebp-20],eax
	sub	esp,28
	mov	ebx,[ebp-88]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1073741824
	push	esi
	fld	[esp]
	pop	esi
	fdivp	st(1)
	mov	esi,1056964608
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+16],ebx
	mov	esi,[ebp-92]
	push	esi
	fld	[esp]
	pop	esi
	mov	edi,1073741824
	push	edi
	fld	[esp]
	pop	edi
	fdivp	st(1)
	mov	edi,1056964608
	push	edi
	fld	[esp]
	pop	edi
	faddp	st(1)
	push	esi
	fstp	[esp]
	pop	esi
	mov	[esp+20],esi
	mov	[esp+24],1065353216
	mov	esi,[ebp-92]
	mov	[esp+12],esi
	mov	ebx,[ebp-60]
	push	ebx
	fld	[esp]
	pop	ebx
	fchs
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+8],ebx
	mov	esi,[ebp-88]
	mov	[esp+4],esi
	mov	eax,[ebp-52]
	mov	[esp],eax
	call	_faddvertex
	mov	[ebp-32],eax
	mov	ebx,[ebp-84]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-56]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-84],ebx
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fcos
	fchs
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-88],eax
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fsin
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-92],eax
	sub	esp,28
	mov	ebx,[ebp-88]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1073741824
	push	esi
	fld	[esp]
	pop	esi
	fdivp	st(1)
	mov	esi,1056964608
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+16],ebx
	mov	esi,[ebp-92]
	push	esi
	fld	[esp]
	pop	esi
	mov	edi,1073741824
	push	edi
	fld	[esp]
	pop	edi
	fdivp	st(1)
	mov	edi,1056964608
	push	edi
	fld	[esp]
	pop	edi
	faddp	st(1)
	push	esi
	fstp	[esp]
	pop	esi
	mov	[esp+20],esi
	mov	[esp+24],1065353216
	mov	esi,[ebp-92]
	mov	[esp+12],esi
	mov	ebx,[ebp-60]
	mov	[esp+8],ebx
	mov	esi,[ebp-88]
	mov	[esp+4],esi
	mov	eax,[ebp-52]
	mov	[esp],eax
	call	_faddvertex
	mov	[ebp-24],eax
	sub	esp,28
	mov	ebx,[ebp-88]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1073741824
	push	esi
	fld	[esp]
	pop	esi
	fdivp	st(1)
	mov	esi,1056964608
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+16],ebx
	mov	esi,[ebp-92]
	push	esi
	fld	[esp]
	pop	esi
	mov	edi,1073741824
	push	edi
	fld	[esp]
	pop	edi
	fdivp	st(1)
	mov	edi,1056964608
	push	edi
	fld	[esp]
	pop	edi
	faddp	st(1)
	push	esi
	fstp	[esp]
	pop	esi
	mov	[esp+20],esi
	mov	[esp+24],1065353216
	mov	esi,[ebp-92]
	mov	[esp+12],esi
	mov	ebx,[ebp-60]
	push	ebx
	fld	[esp]
	pop	ebx
	fchs
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+8],ebx
	mov	esi,[ebp-88]
	mov	[esp+4],esi
	mov	eax,[ebp-52]
	mov	[esp],eax
	call	_faddvertex
	mov	[ebp-36],eax
	mov	[ebp-96],1
	jmp	_43
_44
	mov	ebx,[ebp-84]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-56]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-84],ebx
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fcos
	fchs
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-88],eax
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fsin
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-92],eax
	sub	esp,28
	mov	ebx,[ebp-88]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1073741824
	push	esi
	fld	[esp]
	pop	esi
	fdivp	st(1)
	mov	esi,1056964608
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+16],ebx
	mov	esi,[ebp-92]
	push	esi
	fld	[esp]
	pop	esi
	mov	edi,1073741824
	push	edi
	fld	[esp]
	pop	edi
	fdivp	st(1)
	mov	edi,1056964608
	push	edi
	fld	[esp]
	pop	edi
	faddp	st(1)
	push	esi
	fstp	[esp]
	pop	esi
	mov	[esp+20],esi
	mov	[esp+24],1065353216
	mov	esi,[ebp-92]
	mov	[esp+12],esi
	mov	ebx,[ebp-60]
	mov	[esp+8],ebx
	mov	esi,[ebp-88]
	mov	[esp+4],esi
	mov	eax,[ebp-52]
	mov	[esp],eax
	call	_faddvertex
	mov	[ebp-28],eax
	sub	esp,28
	mov	ebx,[ebp-88]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,1073741824
	push	esi
	fld	[esp]
	pop	esi
	fdivp	st(1)
	mov	esi,1056964608
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+16],ebx
	mov	esi,[ebp-92]
	push	esi
	fld	[esp]
	pop	esi
	mov	edi,1073741824
	push	edi
	fld	[esp]
	pop	edi
	fdivp	st(1)
	mov	edi,1056964608
	push	edi
	fld	[esp]
	pop	edi
	faddp	st(1)
	push	esi
	fstp	[esp]
	pop	esi
	mov	[esp+20],esi
	mov	[esp+24],1065353216
	mov	esi,[ebp-92]
	mov	[esp+12],esi
	mov	ebx,[ebp-60]
	push	ebx
	fld	[esp]
	pop	ebx
	fchs
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[esp+8],ebx
	mov	esi,[ebp-88]
	mov	[esp+4],esi
	mov	eax,[ebp-52]
	mov	[esp],eax
	call	_faddvertex
	mov	[ebp-40],eax
	sub	esp,16
	mov	ebx,[ebp-24]
	mov	[esp+8],ebx
	mov	esi,[ebp-28]
	mov	[esp+12],esi
	mov	esi,[ebp-20]
	mov	[esp+4],esi
	mov	eax,[ebp-52]
	mov	[esp],eax
	call	_faddtriangle
	sub	esp,16
	mov	ebx,[ebp-36]
	mov	[esp+8],ebx
	mov	esi,[ebp-32]
	mov	[esp+12],esi
	mov	esi,[ebp-40]
	mov	[esp+4],esi
	mov	eax,[ebp-52]
	mov	[esp],eax
	call	_faddtriangle
	mov	ebx,[ebp+20]
	sub	ebx,2
	cmp	[ebp-96],ebx
	jge	_45
	mov	ebx,[ebp-28]
	mov	[ebp-24],ebx
	mov	ebx,[ebp-40]
	mov	[ebp-36],ebx
_45
	add	[ebp-96],1
_43
	mov	ebx,[ebp+20]
	sub	ebx,2
	cmp	[ebp-96],ebx
	jle	_44
_10
_42
	mov	ebx,[ebp-60]
	mov	[ebp-100],ebx
	mov	[ebp-84],1119092736
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fcos
	fchs
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-88],eax
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fsin
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-92],eax
	mov	ebx,[ebp-68]
	mov	[ebp-104],ebx
	mov	[ebp-108],0
	sub	esp,28
	mov	ebx,[ebp-108]
	mov	[esp+20],ebx
	mov	[esp+24],1065353216
	mov	esi,[ebp-104]
	mov	[esp+16],esi
	mov	ebx,[ebp-92]
	mov	[esp+12],ebx
	mov	esi,[ebp-100]
	mov	[esp+8],esi
	mov	ebx,[ebp-88]
	mov	[esp+4],ebx
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_faddvertex
	mov	ebx,0
	shl	ebx,byte 2
	add	ebx,[_atring]
	mov	[ebx],eax
	mov	[ebp-96],0
	jmp	_46
_47
	mov	ebx,[ebp-84]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-56]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-84],ebx
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fcos
	fchs
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-88],eax
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fsin
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-92],eax
	mov	ebx,[ebp-104]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-72]
	push	esi
	fld	[esp]
	pop	esi
	fsubp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-104],ebx
	sub	esp,28
	mov	ebx,[ebp-108]
	mov	[esp+20],ebx
	mov	[esp+24],1065353216
	mov	esi,[ebp-104]
	mov	[esp+16],esi
	mov	ebx,[ebp-92]
	mov	[esp+12],ebx
	mov	esi,[ebp-100]
	mov	[esp+8],esi
	mov	ebx,[ebp-88]
	mov	[esp+4],ebx
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_faddvertex
	mov	ebx,[ebp-96]
	add	ebx,1
	shl	ebx,byte 2
	add	ebx,[_atring]
	mov	[ebx],eax
	add	[ebp-96],1
_46
	mov	ebx,[ebp+20]
	sub	ebx,1
	cmp	[ebp-96],ebx
	jle	_47
_11
	mov	[ebp-112],0
	jmp	_48
_49
	mov	ebx,[ebp-100]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-64]
	push	esi
	fld	[esp]
	pop	esi
	fsubp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-100],ebx
	mov	[ebp-84],1119092736
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fcos
	fchs
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-88],eax
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fsin
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-92],eax
	mov	ebx,[ebp-68]
	mov	[ebp-104],ebx
	mov	ebx,[ebp-108]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-80]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-108],ebx
	sub	esp,28
	mov	ebx,[ebp-108]
	mov	[esp+20],ebx
	mov	[esp+24],1065353216
	mov	esi,[ebp-104]
	mov	[esp+16],esi
	mov	ebx,[ebp-92]
	mov	[esp+12],ebx
	mov	esi,[ebp-100]
	mov	[esp+8],esi
	mov	ebx,[ebp-88]
	mov	[esp+4],ebx
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_faddvertex
	mov	ebx,0
	shl	ebx,byte 2
	add	ebx,[_abring]
	mov	[ebx],eax
	mov	[ebp-96],0
	jmp	_50
_51
	mov	ebx,[ebp-84]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-56]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-84],ebx
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fcos
	fchs
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-88],eax
	sub	esp,4
	mov	eax,[ebp-84]
	mov	[esp],eax
	call	_fsin
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-92],eax
	mov	ebx,[ebp-104]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-72]
	push	esi
	fld	[esp]
	pop	esi
	fsubp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-104],ebx
	sub	esp,28
	mov	ebx,[ebp-108]
	mov	[esp+20],ebx
	mov	[esp+24],1065353216
	mov	esi,[ebp-104]
	mov	[esp+16],esi
	mov	ebx,[ebp-92]
	mov	[esp+12],ebx
	mov	esi,[ebp-100]
	mov	[esp+8],esi
	mov	ebx,[ebp-88]
	mov	[esp+4],ebx
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_faddvertex
	mov	ebx,[ebp-96]
	add	ebx,1
	shl	ebx,byte 2
	add	ebx,[_abring]
	mov	[ebx],eax
	add	[ebp-96],1
_50
	mov	ebx,[ebp+20]
	sub	ebx,1
	cmp	[ebp-96],ebx
	jle	_51
_13
	mov	[ebp-116],1
	jmp	_52
_53
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_atring]
	mov	ebx,[ebx]
	mov	[ebp-8],ebx
	mov	ebx,[ebp-116]
	sub	ebx,1
	shl	ebx,byte 2
	add	ebx,[_atring]
	mov	ebx,[ebx]
	mov	[ebp-4],ebx
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_abring]
	mov	ebx,[ebx]
	mov	[ebp-16],ebx
	mov	ebx,[ebp-116]
	sub	ebx,1
	shl	ebx,byte 2
	add	ebx,[_abring]
	mov	ebx,[ebx]
	mov	[ebp-12],ebx
	sub	esp,16
	mov	ebx,[ebp-4]
	mov	[esp+8],ebx
	mov	esi,[ebp-12]
	mov	[esp+12],esi
	mov	esi,[ebp-8]
	mov	[esp+4],esi
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_faddtriangle
	sub	esp,16
	mov	ebx,[ebp-8]
	mov	[esp+8],ebx
	mov	esi,[ebp-12]
	mov	[esp+12],esi
	mov	esi,[ebp-16]
	mov	[esp+4],esi
	mov	eax,[ebp-48]
	mov	[esp],eax
	call	_faddtriangle
	add	[ebp-116],1
_52
	mov	ebx,[ebp+20]
	cmp	[ebp-116],ebx
	jle	_53
_14
	mov	[ebp-116],0
	jmp	_54
_55
	mov	ebx,[ebp-116]
	shl	ebx,byte 2
	add	ebx,[_abring]
	mov	ebx,[ebx]
	mov	esi,[ebp-116]
	shl	esi,byte 2
	add	esi,[_atring]
	mov	[esi],ebx
	add	[ebp-116],1
_54
	mov	ebx,[ebp+20]
	cmp	[ebp-116],ebx
	jle	_55
_15
	add	[ebp-112],1
_48
	mov	ebx,[ebp+24]
	cmp	[ebp-112],ebx
	jle	_49
_12
	sub	esp,4
	mov	eax,[ebp-44]
	mov	[esp],eax
	call	_fupdatenormals
	mov	eax,[ebp-44]
	jmp	_9_leave
	mov	eax,0
	jmp	_9_leave
_9_leave
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 16
	.align	16
_ftunnel_effect
	push	ebx
	push	esi
	push	edi
	push	ebp
	mov	ebp,esp
	sub	esp,52
	mov	ebx,0
	mov	[ebp-4],ebx
	mov	[ebp-8],ebx
	mov	[ebp-12],ebx
	mov	[ebp-16],ebx
	mov	[ebp-20],ebx
	mov	[ebp-24],ebx
	mov	[ebp-28],ebx
	mov	[ebp-32],ebx
	mov	[ebp-36],ebx
	mov	[ebp-40],ebx
	mov	[ebp-44],ebx
	mov	[ebp-48],ebx
	mov	[ebp-52],ebx
	sub	esp,4
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fcountsurfaces
	mov	[ebp-4],eax
	sub	esp,8
	mov	eax,[ebp+20]
	mov	[esp],eax
	mov	ebx,[ebp-4]
	mov	[esp+4],ebx
	call	_fgetsurface
	mov	[ebp-8],eax
	sub	esp,8
	mov	eax,[ebp+24]
	mov	[esp],eax
	mov	ebx,[ebp-4]
	mov	[esp+4],ebx
	call	_fgetsurface
	mov	[ebp-12],eax
	sub	esp,4
	mov	eax,[ebp-8]
	mov	[esp],eax
	call	_fcountvertices
	mov	[ebp-16],eax
	mov	[ebp-20],0
	jmp	_56
_57
	sub	esp,4
	mov	eax,[ebp-20]
	shl	eax,byte 2
	add	eax,[_vctrlpoints]
	mov	eax,[eax]
	mov	eax,[eax]
	add	eax,0
	mov	eax,[eax]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,[ebp+28]
	push	ebx
	fild	[esp]
	pop	ebx
	faddp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp],eax
	call	_fcos
	mov	ebx,1106247680
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-20]
	add	esi,1
	push	esi
	fild	[esp]
	pop	esi
	fdivp	st(1)
	fmulp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-24],eax
	sub	esp,4
	mov	eax,[ebp-20]
	shl	eax,byte 2
	add	eax,[_vctrlpoints]
	mov	eax,[eax]
	mov	eax,[eax]
	add	eax,4
	mov	eax,[eax]
	push	eax
	fld	[esp]
	pop	eax
	mov	ebx,[ebp+32]
	push	ebx
	fild	[esp]
	pop	ebx
	faddp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[esp],eax
	call	_fsin
	mov	ebx,1106247680
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-20]
	add	esi,1
	push	esi
	fild	[esp]
	pop	esi
	fdivp	st(1)
	fmulp	st(1)
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-28],eax
	mov	ebx,[_vvsegs]
	add	ebx,1
	imul	ebx,[ebp-20]
	mov	[ebp-32],ebx
	mov	ebx,[ebp-32]
	add	ebx,[_vvsegs]
	mov	[ebp-36],ebx
	mov	ebx,[ebp-32]
	mov	[ebp-40],ebx
	jmp	_58
_59
	sub	esp,8
	mov	eax,[ebp-12]
	mov	[esp],eax
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	call	_fvertexx
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-44],eax
	sub	esp,8
	mov	eax,[ebp-12]
	mov	[esp],eax
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	call	_fvertexy
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-48],eax
	sub	esp,8
	mov	eax,[ebp-12]
	mov	[esp],eax
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	call	_fvertexz
	push	eax
	fstp	[esp]
	pop	eax
	mov	[ebp-52],eax
	mov	ebx,[ebp-44]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-24]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-44],ebx
	mov	ebx,[ebp-48]
	push	ebx
	fld	[esp]
	pop	ebx
	mov	esi,[ebp-28]
	push	esi
	fld	[esp]
	pop	esi
	faddp	st(1)
	push	ebx
	fstp	[esp]
	pop	ebx
	mov	[ebp-48],ebx
	sub	esp,20
	mov	ebx,[ebp-48]
	mov	[esp+12],ebx
	mov	esi,[ebp-52]
	mov	[esp+16],esi
	mov	esi,[ebp-44]
	mov	[esp+8],esi
	mov	ebx,[ebp-40]
	mov	[esp+4],ebx
	mov	eax,[ebp-8]
	mov	[esp],eax
	call	_fvertexcoords
	add	[ebp-40],1
_58
	mov	ebx,[ebp-36]
	cmp	[ebp-40],ebx
	jle	_59
_18
	add	[ebp-20],1
_56
	mov	ebx,[_vrsegs]
	cmp	[ebp-20],ebx
	jle	_57
_17
	sub	esp,4
	mov	eax,[ebp+20]
	mov	[esp],eax
	call	_fupdatenormals
	mov	eax,0
	jmp	_16_leave
_16_leave
	mov	esp,ebp
	pop	ebp
	pop	edi
	pop	esi
	pop	ebx
	ret	word 16
	.align	4
_atring	.dd	0
	.dd	1
	.dd	1
	.dd	0
	.align	4
_abring	.dd	0
	.dd	1
	.dd	1
	.dd	0
	.align	4
_3	.dd	6
	.dd	17
	.dd	_ttctrlpoint
_vctrlpoints	.dd	0
	.align	4
_vctrlpointsphase	.dd	0
	.align	4
_vctrlpointsphase2	.dd	0
	.align	4
_vvsegs	.dd	0
	.align	4
_vrsegs	.dd	0
	.align	4
_ttctrlpoint	.dd	5
_37	.dd	0
	.dd	_37
	.dd	_37
	.dd	0
	.dd	-1
_38	.dd	0
	.dd	_38
	.dd	_38
	.dd	0
	.dd	-1
	.dd	2
	.dd	__bbFltType
	.dd	__bbFltType
	.align	4
__LIBS
	.db	"",0
	.align	4
__DATA
	.dd	0

